# Generated by Django 4.2.27 on 2026-08-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_analysis', '0021_datasource_builtin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourceapimodel',
            name='source_type',
            field=models.CharField(choices=[('nats', 'NATS'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('rest_api', 'REST API'), ('excel', 'Excel'), ('prometheus', 'Prometheus')], default='nats', max_length=32, verbose_name='数据来源类型'),
        ),
    ]
