# Generated by Django 4.2.27 on 2026-08-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_analysis', '0023_remove_trend_group_by_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('groups', models.JSONField(blank=True, default=list, help_text='组织', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='数据连接名称')),
                ('connection_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('rest_api', 'REST API')], max_length=32, verbose_name='连接类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='连接配置')),
            ],
            options={
                'verbose_name': '数据连接',
                'db_table': 'operation_analysis_data_connection',
            },
        ),
        migrations.AddField(
            model_name='datasourceapimodel',
            name='connection_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name='连接覆盖项'),
        ),
        migrations.AddField(
            model_name='datasourceapimodel',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_sources', to='operation_analysis.dataconnection', verbose_name='数据连接'),
        ),
    ]
