# Generated by Django 4.2.27 on 2026-08-13 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operation_analysis", "0026_excel_materialization_slot"),
        ("operation_analysis", "0026_merge_20260812_0400"),
    ]

    operations = []
