/** Host theme tokens with fallbacks for standalone embed. */
export const WC = {
  indigo: 'var(--color-primary, #155AEF)',
  indigoHi: 'var(--color-primary, #155AEF)',
  purple: 'var(--color-primary, #155AEF)',
  headerEnd: 'var(--color-primary, #155AEF)',
  onPrimary: 'var(--color-primary-foreground, #ffffff)',
  onPrimaryHover: 'var(--color-bg-6, rgba(255,255,255,0.16))',
  primaryBg: 'var(--color-primary-bg-active, #e1edfc)',
  headerBg: 'linear-gradient(180deg, color-mix(in srgb, var(--color-primary, #155AEF) 7%, var(--color-bg, #ffffff)) 0%, var(--color-bg, #ffffff) 100%)',
  headerInk: 'var(--color-text-1, #1e252e)',
  stage: 'var(--color-bg, #ffffff)',
  composerWash: 'var(--color-bg, #ffffff)',
  historyRail: 'var(--color-fill-1, #f6f8f9)',
  thinkLine: 'var(--color-border-1, #edeff3)',
  white: 'var(--color-bg, #ffffff)',
  page: 'var(--color-fill-1, #f6f8f9)',
  botBubble: 'var(--color-fill-2, #f4f5f8)',
  botText: 'var(--color-text-1, #1e252e)',
  inkSoft: 'var(--color-text-2, #4e5969)',
  botBorder: 'var(--color-border-1, #edeff3)',
  dockEdge: 'var(--color-border-3, #d1d7e1)',
  dockShadow: '-8px 0 12px color-mix(in srgb, var(--color-text-1, #1e252e) 14%, transparent)',
  muted: 'var(--color-text-3, #7588a3)',
  dim: 'var(--color-text-4, #B2BDCC)',
  fail: 'var(--color-fail, #F43B2C)',
  success: 'var(--color-success, #27c274)',
  warning: 'var(--theme-color-status-warning, #FAAD14)',
  warningBg: 'color-mix(in srgb, var(--theme-color-status-warning, #FAAD14) 16%, var(--color-bg, #ffffff))',
  overlay: 'color-mix(in srgb, var(--color-text-1, #1e252e) 48%, transparent)',
  shadow: '0 18px 50px var(--color-portal-card-shadow, rgba(33,59,99,0.18))',
  toolBg: 'color-mix(in srgb, var(--color-success, #27c274) 14%, var(--color-bg, #ffffff))',
  toolText: 'var(--color-success, #27c274)',
  toolBorder: 'color-mix(in srgb, var(--color-success, #27c274) 35%, var(--color-border-1, #edeff3))',
} as const;
