# Generated by Django 4.2.27 on 2026-07-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0020_actionrule_actionexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyresult',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='通知失败原因', null=True),
        ),
    ]
