# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


def backfill_active_fingerprints(apps, schema_editor):
    Alert = apps.get_model("alerts", "Alert")
    Lease = apps.get_model("alerts", "ActiveAlertFingerprint")
    active_statuses = ("unassigned", "pending", "processing")
    rows = (
        Alert.objects.filter(status__in=active_statuses)
        .order_by("fingerprint", "-updated_at")
        .values_list("fingerprint", "id")
        .iterator(chunk_size=500)
    )
    for fingerprint, alert_id in rows:
        Lease.objects.get_or_create(
            fingerprint=fingerprint, defaults={"alert_id": alert_id}
        )


class Migration(migrations.Migration):
    dependencies = [("alerts", "0020_actionrule_actionexecution")]

    operations = [
        migrations.CreateModel(
            name="ActiveAlertFingerprint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("fingerprint", models.CharField(max_length=32, unique=True)),
                (
                    "alert",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_fingerprint_lease",
                        to="alerts.alert",
                    ),
                ),
            ],
            options={"db_table": "alerts_active_fingerprint"},
        ),
        migrations.RunPython(backfill_active_fingerprints, migrations.RunPython.noop),
        migrations.CreateModel(
            name="AlertOutbox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("kind", models.CharField(db_index=True, max_length=32)),
                ("payload", models.JSONField(default=dict)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(choices=[("pending", "待投递"), ("delivering", "投递中"), ("delivered", "已投递"), ("failed", "投递失败")], db_index=True, default="pending", max_length=16)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=8)),
                ("next_retry_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "alerts_outbox",
                "indexes": [models.Index(fields=["status", "next_retry_at"], name="alert_outbox_retry_idx")],
            },
        ),
    ]
