# Generated by Django 4.2.27 on 2026-07-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0021_activealertfingerprint'),
        ('alerts', '0021_notifyresult_failure_reason'),
    ]

    operations = [
    ]
