# Generated by Django 4.2.27 on 2026-08-14

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0022_merge_20260717_0921"),
    ]

    operations = [
        migrations.CreateModel(
            name="K8sInstallToken",
            fields=[
                (
                    "token_hash",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="令牌摘要",
                    ),
                ),
                ("encrypted_payload", models.TextField(verbose_name="加密渲染参数")),
                (
                    "usage_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="已使用次数"),
                ),
                (
                    "max_usage",
                    models.PositiveSmallIntegerField(default=5, verbose_name="最大使用次数"),
                ),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="过期时间")),
            ],
            options={
                "verbose_name": "告警 K8s 安装令牌",
                "verbose_name_plural": "告警 K8s 安装令牌",
                "db_table": "alerts_k8s_install_token",
            },
        ),
        migrations.AddConstraint(
            model_name="k8sinstalltoken",
            constraint=models.CheckConstraint(
                check=models.Q(("max_usage__gt", 0)),
                name="alerts_k8s_token_max_usage_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="k8sinstalltoken",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("usage_count__lte", django.db.models.expressions.F("max_usage"))
                ),
                name="alerts_k8s_token_usage_lte_max",
            ),
        ),
    ]
