import type { SimpleDashboardConfig } from '../common/simple-dashboard-core';

const HTTP_PROBE_ENUM = {
  0: { label: '成功', color: '#27c274' },
  1: { label: '内容不匹配', color: '#faad14' },
  2: { label: '读取失败', color: '#faad14' },
  3: { label: '连接失败', color: '#ff4d4f' },
  4: { label: '超时', color: '#ff4d4f' },
  5: { label: 'DNS 错误', color: '#ff4d4f' },
  6: { label: '状态码不匹配', color: '#faad14' },
};

export const EXCHANGE_DASHBOARD_CONFIG: SimpleDashboardConfig = {
  routeKey: 'exchange',
  pageTitle: 'Exchange 监控仪表盘',
  objectFallbackName: 'Exchange',
  instanceType: 'exchange',
  collectionStatusQuery: "count({instance_type='exchange', collect_type='host', __$labels__}) by (instance_id)",
  metaItems: ['Telegraf', 'host', 'Transport', 'CAS'],
  metrics: [
    {
      name: 'exchange_active_mailbox_delivery_queue_length',
      display_name: '邮箱投递队列',
      description: '活动邮箱投递队列长度。',
      unit: 'counts',
      query: 'win_exchange_transport_queues_Active_Mailbox_Delivery_Queue_Length{instance_type="exchange", __$labels__}',
      color: '#2f6bff',
    },
    {
      name: 'exchange_retry_mailbox_delivery_queue_length',
      display_name: '重试投递队列',
      description: '重试邮箱投递队列长度。',
      unit: 'counts',
      query: 'win_exchange_transport_queues_Retry_Mailbox_Delivery_Queue_Length{instance_type="exchange", __$labels__}',
      color: '#ff8a1f',
    },
    {
      name: 'exchange_poison_queue_length',
      display_name: 'Poison 队列',
      description: 'Poison 队列长度，非零需立即排查。',
      unit: 'counts',
      query: 'win_exchange_transport_queues_Poison_Queue_Length{instance_type="exchange", __$labels__}',
      color: '#ff4d4f',
    },
    {
      name: 'exchange_unreachable_queue_length',
      display_name: '不可达队列',
      description: '不可达队列长度。',
      unit: 'counts',
      query: 'win_exchange_transport_queues_Unreachable_Queue_Length{instance_type="exchange", __$labels__}',
      color: '#faad14',
    },
    {
      name: 'exchange_submission_queue_length',
      display_name: '提交队列',
      description: '邮件提交队列长度。',
      unit: 'counts',
      query: 'win_exchange_transport_queues_Submission_Queue_Length{instance_type="exchange", __$labels__}',
      color: '#597ef7',
    },
    {
      name: 'exchange_owa_current_unique_users',
      display_name: 'OWA 在线用户',
      description: 'OWA 当前唯一登录用户数。',
      unit: 'counts',
      query: 'win_exchange_owa_Current_Unique_Users{instance_type="exchange", __$labels__}',
      color: '#27c274',
    },
    {
      name: 'exchange_owa_requests_persec',
      display_name: 'OWA 请求速率',
      description: 'OWA 每秒请求数。',
      unit: 'cps',
      query: 'win_exchange_owa_Requests_persec{instance_type="exchange", __$labels__}',
      color: '#13c2c2',
    },
    {
      name: 'exchange_mapihttp_active_user_count',
      display_name: 'MAPI 活跃用户',
      description: 'MAPI HTTP 当前活跃用户数。',
      unit: 'counts',
      query: 'win_exchange_mapihttp_Active_User_Count{instance_type="exchange", __$labels__}',
      color: '#8a5cff',
    },
    {
      name: 'exchange_activesync_requests_persec',
      display_name: 'ActiveSync 请求',
      description: 'ActiveSync 每秒请求数。',
      unit: 'cps',
      query: 'win_exchange_activesync_Requests_persec{instance_type="exchange", __$labels__}',
      color: '#722ed1',
    },
    {
      name: 'exchange_autodiscover_requests_persec',
      display_name: 'Autodiscover 请求',
      description: 'Autodiscover 每秒请求数。',
      unit: 'cps',
      query: 'win_exchange_autodiscover_Requests_persec{instance_type="exchange", __$labels__}',
      color: '#597ef7',
    },
    {
      name: 'exchange_availability_requests_sec',
      display_name: 'Availability 请求',
      description: 'Availability Service 每秒请求数。',
      unit: 'cps',
      query: 'win_exchange_availability_Availability_Requests_(sec){instance_type="exchange", __$labels__}',
      color: '#2f6bff',
    },
    {
      name: 'exchange_http_proxy_outstanding_proxy_requests',
      display_name: 'HttpProxy 排队',
      description: 'HttpProxy 未完成代理请求数。',
      unit: 'counts',
      query: 'win_exchange_http_proxy_Outstanding_Proxy_Requests{instance_type="exchange", __$labels__}',
      color: '#ff8a1f',
    },
    {
      name: 'exchange_http_proxy_avg_auth_latency',
      display_name: 'HttpProxy 认证延迟',
      description: 'HttpProxy 平均认证延迟（毫秒）。',
      unit: 'ms',
      query: 'win_exchange_http_proxy_Average_Authentication_Latency{instance_type="exchange", __$labels__}',
      color: '#faad14',
    },
    {
      name: 'exchange_http_proxy_requests_persec',
      display_name: 'HttpProxy 请求',
      description: 'HttpProxy 每秒代理请求数。',
      unit: 'cps',
      query: 'win_exchange_http_proxy_Proxy_Requests_persec{instance_type="exchange", __$labels__}',
      color: '#13c2c2',
    },
    {
      name: 'exchange_adaccess_ldap_timeout_errors_persec',
      display_name: 'AD LDAP 超时',
      description: 'ADAccess 进程 LDAP 超时错误速率。',
      unit: 'cps',
      query: 'win_exchange_adaccess_LDAP_Timeout_Errors_persec{instance_type="exchange", __$labels__}',
      color: '#ff4d4f',
    },
    {
      name: 'exchange_adaccess_ldap_read_time',
      display_name: 'AD LDAP 读延迟',
      description: 'ADAccess 进程 LDAP 读操作耗时（毫秒）。',
      unit: 'ms',
      query: 'win_exchange_adaccess_LDAP_Read_Time{instance_type="exchange", __$labels__}',
      color: '#ff8a1f',
    },
    {
      name: 'exchange_workload_active_tasks',
      display_name: 'Workload 活跃任务',
      description: 'Workload Management 活跃任务数。',
      unit: 'counts',
      query: 'win_exchange_workload_ActiveTasks{instance_type="exchange", __$labels__}',
      color: '#27c274',
    },
    {
      name: 'exchange_workload_queued_tasks',
      display_name: 'Workload 排队任务',
      description: 'Workload Management 排队任务数。',
      unit: 'counts',
      query: 'win_exchange_workload_QueuedTasks{instance_type="exchange", __$labels__}',
      color: '#faad14',
    },
    {
      name: 'exchange_owa_probe_result_code',
      display_name: 'OWA 探测状态',
      description: '本地 OWA HTTP 探测结果，0 表示成功。',
      unit: 'none',
      query: 'http_response_result_code{instance_type="exchange", endpoint="owa", __$labels__}',
      color: '#27c274',
    },
    {
      name: 'exchange_ews_probe_result_code',
      display_name: 'EWS 探测状态',
      description: '本地 EWS HTTP 探测结果，0 表示成功。',
      unit: 'none',
      query: 'http_response_result_code{instance_type="exchange", endpoint="ews", __$labels__}',
      color: '#27c274',
    },
    {
      name: 'exchange_owa_probe_response_time',
      display_name: 'OWA 探测耗时',
      description: 'OWA HTTP 探测响应时间（秒）。',
      unit: 's',
      query: 'http_response_response_time{instance_type="exchange", endpoint="owa", __$labels__}',
      color: '#ff8a1f',
    },
    {
      name: 'exchange_ews_probe_response_time',
      display_name: 'EWS 探测耗时',
      description: 'EWS HTTP 探测响应时间（秒）。',
      unit: 's',
      query: 'http_response_response_time{instance_type="exchange", endpoint="ews", __$labels__}',
      color: '#8a5cff',
    },
  ],
  summaryCards: [
    {
      title: '邮箱投递队列',
      metric: 'exchange_active_mailbox_delivery_queue_length',
      unit: 'counts',
      color: '#2f6bff',
      icon: 'database',
      compare: true,
      compareFavorableDirection: 'down',
      guide: [{ label: '邮件流', detail: 'Hub Transport 活动投递队列；Datadog Exchange 集成中的 Mail Flow 核心 KPI。' }],
      footer: [{ label: '提交队列', metric: 'exchange_submission_queue_length', unit: 'counts' }],
    },
    {
      title: 'Poison 队列',
      metric: 'exchange_poison_queue_length',
      unit: 'counts',
      color: '#ff4d4f',
      icon: 'api',
      compare: true,
      compareFavorableDirection: 'down',
      guide: [{ label: 'Poison', detail: '不可投递异常邮件队列；Grafana Exchange 模板中需置顶的 Critical 信号，非零即告警。' }],
      footer: [{ label: '不可达', metric: 'exchange_unreachable_queue_length', unit: 'counts' }],
    },
    {
      title: 'OWA 在线用户',
      metric: 'exchange_owa_current_unique_users',
      unit: 'counts',
      color: '#27c274',
      icon: 'node',
      compare: true,
      guide: [{ label: 'CAS 负载', detail: 'OWA 唯一在线用户，反映 Outlook Web 访问活跃度。' }],
      footer: [{ label: 'MAPI 用户', metric: 'exchange_mapihttp_active_user_count', unit: 'counts' }],
    },
    {
      title: 'AD LDAP 超时',
      metric: 'exchange_adaccess_ldap_timeout_errors_persec',
      unit: 'cps',
      color: '#ff4d4f',
      icon: 'thunder',
      compare: true,
      compareFavorableDirection: 'down',
      guide: [{ label: 'AD 依赖', detail: 'Exchange 对 Active Directory 的 LDAP 超时错误；升高说明邮件服务受域控影响。' }],
      footer: [{ label: 'LDAP 读延迟', metric: 'exchange_adaccess_ldap_read_time', unit: 'ms' }],
    },
    {
      title: 'OWA 探测',
      metric: 'exchange_owa_probe_result_code',
      color: '#27c274',
      icon: 'api',
      enumMap: HTTP_PROBE_ENUM,
      guide: [{ label: 'Synthetic', detail: '本地 OWA HTTP 合成探测，类似 Datadog Synthetics / Grafana blackbox。' }],
      footer: [{ label: 'EWS', metric: 'exchange_ews_probe_result_code', enumMap: HTTP_PROBE_ENUM }],
    },
  ],
  charts: [
    {
      title: '传输队列全景',
      subtitle: '投递 / 重试 / Poison / 不可达 / 提交',
      metric: 'exchange_active_mailbox_delivery_queue_length',
      guide: [{ label: 'Mail Flow', detail: 'MSExchangeTransport 各队列长度；Poison/不可达非零需优先处理。' }],
      series: [
        { metric: 'exchange_active_mailbox_delivery_queue_length', label: '活动投递', color: '#2f6bff', unit: 'counts' },
        { metric: 'exchange_retry_mailbox_delivery_queue_length', label: '重试投递', color: '#ff8a1f', unit: 'counts' },
        { metric: 'exchange_poison_queue_length', label: 'Poison', color: '#ff4d4f', unit: 'counts' },
        { metric: 'exchange_unreachable_queue_length', label: '不可达', color: '#faad14', unit: 'counts' },
        { metric: 'exchange_submission_queue_length', label: '提交队列', color: '#13c2c2', unit: 'counts' },
      ],
    },
    {
      title: '客户端访问',
      subtitle: 'OWA / MAPI / ActiveSync',
      metric: 'exchange_owa_current_unique_users',
      guide: [{ label: 'CAS', detail: 'Outlook Web、MAPI HTTP 与 ActiveSync 并发，反映客户端接入压力。' }],
      series: [
        { metric: 'exchange_owa_current_unique_users', label: 'OWA 用户', color: '#27c274', unit: 'counts' },
        { metric: 'exchange_mapihttp_active_user_count', label: 'MAPI 用户', color: '#8a5cff', unit: 'counts' },
        { metric: 'exchange_activesync_requests_persec', label: 'ActiveSync/s', color: '#722ed1', unit: 'cps' },
      ],
    },
    {
      title: 'HttpProxy 性能',
      subtitle: '请求 / 排队 / 认证延迟',
      metric: 'exchange_http_proxy_requests_persec',
      guide: [{ label: '反向代理', detail: 'Exchange HttpProxy 层请求速率、排队与认证延迟。' }],
      series: [
        { metric: 'exchange_http_proxy_requests_persec', label: '代理请求/s', color: '#13c2c2', unit: 'cps' },
        { metric: 'exchange_http_proxy_outstanding_proxy_requests', label: '排队请求', color: '#ff8a1f', unit: 'counts' },
        { metric: 'exchange_http_proxy_avg_auth_latency', label: '认证延迟', color: '#faad14', unit: 'ms' },
      ],
    },
    {
      title: '协议与服务发现',
      subtitle: 'OWA / Autodiscover / Availability',
      metric: 'exchange_owa_requests_persec',
      guide: [{ label: '协议请求', detail: 'OWA、Autodiscover 与 Availability Service 请求速率。' }],
      series: [
        { metric: 'exchange_owa_requests_persec', label: 'OWA 请求/s', color: '#13c2c2', unit: 'cps' },
        { metric: 'exchange_autodiscover_requests_persec', label: 'Autodiscover/s', color: '#597ef7', unit: 'cps' },
        { metric: 'exchange_availability_requests_sec', label: 'Availability/s', color: '#2f6bff', unit: 'cps' },
      ],
    },
    {
      title: 'AD 目录依赖',
      subtitle: 'LDAP 超时 / 读延迟',
      metric: 'exchange_adaccess_ldap_timeout_errors_persec',
      guide: [{ label: 'ADAccess', detail: 'Exchange 访问 AD 的超时错误与读延迟，是跨服务根因分析的关键链路。' }],
      series: [
        { metric: 'exchange_adaccess_ldap_timeout_errors_persec', label: 'LDAP 超时/s', color: '#ff4d4f', unit: 'cps' },
        { metric: 'exchange_adaccess_ldap_read_time', label: 'LDAP 读延迟', color: '#ff8a1f', unit: 'ms' },
      ],
    },
    {
      title: 'Workload 任务',
      subtitle: '活跃 / 排队',
      metric: 'exchange_workload_active_tasks',
      guide: [{ label: '后台任务', detail: 'Exchange Workload Management 活跃与排队任务数，反映后台处理压力。' }],
      series: [
        { metric: 'exchange_workload_active_tasks', label: '活跃任务', color: '#27c274', unit: 'counts' },
        { metric: 'exchange_workload_queued_tasks', label: '排队任务', color: '#ff8a1f', unit: 'counts' },
      ],
    },
    {
      title: 'Synthetic 端点延迟',
      subtitle: 'OWA / EWS 探测 RTT',
      metric: 'exchange_owa_probe_response_time',
      guide: [{ label: 'Synthetic', detail: 'OWA 与 EWS HTTP 合成探测往返时延；同卡分序列展示，便于对比各端点 SLO。' }],
      series: [
        { metric: 'exchange_owa_probe_response_time', label: 'OWA RTT', color: '#ff8a1f', unit: 's' },
        { metric: 'exchange_ews_probe_response_time', label: 'EWS RTT', color: '#8a5cff', unit: 's' },
      ],
    },
  ],
  ringPanels: [
    {
      title: '传输队列构成',
      subtitle: '活动 / 重试 / Poison',
      centerMetric: 'exchange_active_mailbox_delivery_queue_length',
      centerCaption: '活动投递',
      centerUnit: 'counts',
      guide: [{ label: '队列占比', detail: '按当前队列深度拆分邮件传输各环节，快速识别积压点。' }],
      segments: [
        { label: '活动投递', metric: 'exchange_active_mailbox_delivery_queue_length', color: '#2f6bff', unit: 'counts' },
        { label: '重试投递', metric: 'exchange_retry_mailbox_delivery_queue_length', color: '#ff8a1f', unit: 'counts' },
        { label: 'Poison', metric: 'exchange_poison_queue_length', color: '#ff4d4f', unit: 'counts' },
      ],
    },
  ],
  barPanels: [],
  statusPanels: [],
  details: [],
};
