"""画布报告订阅资源类型常量。"""

RESOURCE_TYPE_DASHBOARD = "dashboard"
RESOURCE_TYPE_SCREEN = "screen"
RESOURCE_TYPE_REPORT = "report"

# Phase 3+：允许写入 dashboard、screen 与 report。
WRITABLE_RESOURCE_TYPES = frozenset({RESOURCE_TYPE_DASHBOARD, RESOURCE_TYPE_SCREEN, RESOURCE_TYPE_REPORT})
# 兼容旧名
PHASE2_WRITABLE_RESOURCE_TYPES = WRITABLE_RESOURCE_TYPES

KNOWN_RESOURCE_TYPES = frozenset({RESOURCE_TYPE_DASHBOARD, RESOURCE_TYPE_SCREEN, RESOURCE_TYPE_REPORT})

DEFAULT_RENDER_SCHEMA_VERSION = 1

# Screen PDF 策略 2：A4 landscape 单页等比 fit（与 Dashboard 视口语义独立）
SCREEN_PDF_FORMAT = "A4"
SCREEN_PDF_LANDSCAPE = True
SCREEN_PDF_SINGLE_PAGE = True
# A4 landscape @ 96dpi（CSS px），用于计算 fit scale
SCREEN_PDF_PAGE_WIDTH_PX = 1122.52
SCREEN_PDF_PAGE_HEIGHT_PX = 793.7
