import type { SimpleDashboardConfig } from '../common/simple-dashboard-core';

const LDAP_PROBE_ENUM = {
  0: { label: '成功', color: '#27c274' },
  1: { label: '超时', color: '#ff4d4f' },
  2: { label: '连接失败', color: '#ff4d4f' },
  3: { label: '读取失败', color: '#ff4d4f' },
  4: { label: '返回不匹配', color: '#faad14' },
};

export const ACTIVE_DIRECTORY_DASHBOARD_CONFIG: SimpleDashboardConfig = {
  routeKey: 'active-directory',
  pageTitle: 'Active Directory 监控仪表盘',
  objectFallbackName: 'Active Directory',
  instanceType: 'active_directory',
  collectionStatusQuery: "count({instance_type='active_directory', collect_type='host', __$labels__}) by (instance_id)",
  metaItems: ['Telegraf', 'host', 'NTDS', 'DRA'],
  metrics: [
    {
      name: 'ad_ldap_successful_binds_persec',
      display_name: 'LDAP 成功绑定',
      description: '域控每秒 LDAP 成功绑定次数。',
      unit: 'cps',
      query: 'win_ad_LDAP_Successful_Binds_persec{instance_type="active_directory", __$labels__}',
      color: '#2f6bff',
    },
    {
      name: 'ad_ldap_client_sessions',
      display_name: 'LDAP 客户端会话',
      description: '当前 LDAP 客户端会话数量。',
      unit: 'counts',
      query: 'win_ad_LDAP_Client_Sessions{instance_type="active_directory", __$labels__}',
      color: '#27c274',
    },
    {
      name: 'ad_ldap_bind_time',
      display_name: 'LDAP 绑定耗时',
      description: '最近一次 LDAP 绑定耗时（毫秒）。',
      unit: 'ms',
      query: 'win_ad_LDAP_Bind_Time{instance_type="active_directory", __$labels__}',
      color: '#ff8a1f',
    },
    {
      name: 'ad_ldap_searches_persec',
      display_name: 'LDAP 搜索',
      description: '每秒 LDAP 搜索次数。',
      unit: 'cps',
      query: 'win_ad_LDAP_Searches_persec{instance_type="active_directory", __$labels__}',
      color: '#13c2c2',
    },
    {
      name: 'ad_ldap_writes_persec',
      display_name: 'LDAP 写入',
      description: '每秒 LDAP 写入次数。',
      unit: 'cps',
      query: 'win_ad_LDAP_Writes_persec{instance_type="active_directory", __$labels__}',
      color: '#722ed1',
    },
    {
      name: 'ad_ldap_new_connections_persec',
      display_name: 'LDAP 新连接',
      description: '每秒新建 LDAP 连接数。',
      unit: 'cps',
      query: 'win_ad_LDAP_New_Connections_persec{instance_type="active_directory", __$labels__}',
      color: '#597ef7',
    },
    {
      name: 'ad_ds_threads_in_use',
      display_name: '目录服务线程',
      description: '当前目录服务正在使用的线程数。',
      unit: 'counts',
      query: 'win_ad_DS_Threads_in_Use{instance_type="active_directory", __$labels__}',
      color: '#8a5cff',
    },
    {
      name: 'ad_ds_notify_queue_size',
      display_name: 'Notify 队列',
      description: '目录服务 notify 队列长度。',
      unit: 'counts',
      query: 'win_ad_DS_Notify_Queue_Size{instance_type="active_directory", __$labels__}',
      color: '#faad14',
    },
    {
      name: 'ad_ds_directory_reads_persec',
      display_name: '目录读取',
      description: '每秒目录读取次数。',
      unit: 'cps',
      query: 'win_ad_DS_Directory_Reads_persec{instance_type="active_directory", __$labels__}',
      color: '#2f6bff',
    },
    {
      name: 'ad_ds_directory_searches_persec',
      display_name: '目录搜索',
      description: '每秒目录搜索次数。',
      unit: 'cps',
      query: 'win_ad_DS_Directory_Searches_persec{instance_type="active_directory", __$labels__}',
      color: '#13c2c2',
    },
    {
      name: 'ad_ds_directory_writes_persec',
      display_name: '目录写入',
      description: '每秒目录写入次数。',
      unit: 'cps',
      query: 'win_ad_DS_Directory_Writes_persec{instance_type="active_directory", __$labels__}',
      color: '#722ed1',
    },
    {
      name: 'ad_dra_pending_replication_operations',
      display_name: '待复制操作',
      description: '域控上尚未完成的复制操作数。',
      unit: 'counts',
      query: 'win_ad_DRA_Pending_Replication_Operations{instance_type="active_directory", __$labels__}',
      color: '#ff4d4f',
    },
    {
      name: 'ad_dra_pending_replication_synchronizations',
      display_name: '待复制同步',
      description: '域控上尚未完成的复制同步数。',
      unit: 'counts',
      query: 'win_ad_DRA_Pending_Replication_Synchronizations{instance_type="active_directory", __$labels__}',
      color: '#ff8a1f',
    },
    {
      name: 'ad_dra_inbound_bytes_total_persec',
      display_name: '入站复制流量',
      description: '入站 AD 复制字节速率。',
      unit: 'byteps',
      query: 'win_ad_DRA_Inbound_Bytes_Total_persec{instance_type="active_directory", __$labels__}',
      color: '#27c274',
    },
    {
      name: 'ad_dra_outbound_bytes_total_persec',
      display_name: '出站复制流量',
      description: '出站 AD 复制字节速率。',
      unit: 'byteps',
      query: 'win_ad_DRA_Outbound_Bytes_Total_persec{instance_type="active_directory", __$labels__}',
      color: '#2f6bff',
    },
    {
      name: 'ad_dra_inbound_full_sync_objects_remaining',
      display_name: '全量同步剩余对象',
      description: '入站全量同步尚未完成的对象数。',
      unit: 'counts',
      query: 'win_ad_DRA_Inbound_Full_Sync_Objects_Remaining{instance_type="active_directory", __$labels__}',
      color: '#faad14',
    },
    {
      name: 'ad_atq_outstanding_queued_requests',
      display_name: 'ATQ 排队请求',
      description: 'ATQ 当前排队中的请求数。',
      unit: 'counts',
      query: 'win_ad_ATQ_Outstanding_Queued_Requests{instance_type="active_directory", __$labels__}',
      color: '#ff8a1f',
    },
    {
      name: 'ad_atq_estimated_queue_delay',
      display_name: 'ATQ 队列延迟',
      description: 'ATQ 估算队列延迟（毫秒）。',
      unit: 'ms',
      query: 'win_ad_ATQ_Estimated_Queue_Delay{instance_type="active_directory", __$labels__}',
      color: '#ff4d4f',
    },
    {
      name: 'ad_ldap_probe_result_code',
      display_name: 'LDAP 探测状态',
      description: '本地 LDAP TCP 探测结果，0 表示成功。',
      unit: 'none',
      query: 'net_response_result_code{instance_type="active_directory", endpoint="ldap", __$labels__}',
      color: '#27c274',
    },
    {
      name: 'ad_ldaps_probe_result_code',
      display_name: 'LDAPS 探测状态',
      description: '本地 LDAPS TCP 探测结果，0 表示成功。',
      unit: 'none',
      query: 'net_response_result_code{instance_type="active_directory", endpoint="ldaps", __$labels__}',
      color: '#27c274',
    },
    {
      name: 'ad_ldap_probe_response_time',
      display_name: 'LDAP 探测耗时',
      description: 'LDAP TCP 探测响应时间（毫秒）。',
      unit: 'ms',
      query: 'net_response_response_time{instance_type="active_directory", endpoint="ldap", __$labels__} * 1000',
      color: '#ff8a1f',
    },
    {
      name: 'ad_ldaps_probe_response_time',
      display_name: 'LDAPS 探测耗时',
      description: 'LDAPS TCP 探测响应时间（毫秒）。',
      unit: 'ms',
      query: 'net_response_response_time{instance_type="active_directory", endpoint="ldaps", __$labels__} * 1000',
      color: '#8a5cff',
    },
  ],
  summaryCards: [
    {
      title: 'LDAP 成功绑定',
      metric: 'ad_ldap_successful_binds_persec',
      unit: 'cps',
      color: '#2f6bff',
      icon: 'node',
      compare: true,
      guide: [{ label: '认证吞吐', detail: '域控每秒 LDAP 成功绑定次数，对应 Grafana NTDS LDAP Successful Binds/sec。' }],
      footer: [{ label: '新连接', metric: 'ad_ldap_new_connections_persec', unit: 'cps' }],
    },
    {
      title: 'LDAP 客户端会话',
      metric: 'ad_ldap_client_sessions',
      unit: 'counts',
      color: '#27c274',
      icon: 'node',
      compare: true,
      guide: [{ label: '会话占用', detail: '当前 LDAP 客户端会话数，持续抬升说明连接池或客户端占用增加。' }],
      footer: [{ label: '绑定耗时', metric: 'ad_ldap_bind_time', unit: 'ms' }],
    },
    {
      title: '复制积压',
      metric: 'ad_dra_pending_replication_operations',
      unit: 'counts',
      color: '#ff4d4f',
      icon: 'api',
      compare: true,
      compareFavorableDirection: 'down',
      guide: [{ label: 'DRA 积压', detail: '待完成复制操作数；Datadog/Grafana 域控健康看板的核心告警信号，非零需排查复制拓扑。' }],
      footer: [{ label: '待同步', metric: 'ad_dra_pending_replication_synchronizations', unit: 'counts' }],
    },
    {
      title: 'ATQ 队列延迟',
      metric: 'ad_atq_estimated_queue_delay',
      unit: 'ms',
      color: '#ff8a1f',
      icon: 'thunder',
      compare: true,
      compareFavorableDirection: 'down',
      guide: [{ label: '请求排队', detail: 'ATQ 估算队列延迟，升高表示 LDAP 请求在域控内部排队变长。' }],
      footer: [{ label: '排队请求', metric: 'ad_atq_outstanding_queued_requests', unit: 'counts' }],
    },
    {
      title: 'LDAP 探测',
      metric: 'ad_ldap_probe_result_code',
      color: '#27c274',
      icon: 'api',
      enumMap: LDAP_PROBE_ENUM,
      guide: [{ label: '端点可达', detail: '本地 LDAP(389) TCP 探测；与 Grafana blackbox/LDAP 探针同类 SLO 信号。' }],
      footer: [{ label: 'LDAPS', metric: 'ad_ldaps_probe_result_code', enumMap: LDAP_PROBE_ENUM }],
    },
  ],
  charts: [
    {
      title: 'LDAP 认证与操作',
      subtitle: '绑定 / 搜索 / 写入 / 新连接 / 绑定耗时',
      metric: 'ad_ldap_successful_binds_persec',
      guide: [{ label: 'LDAP 操作', detail: '认证绑定与目录读写速率；绑定耗时右轴语义通过独立序列呈现。' }],
      series: [
        { metric: 'ad_ldap_successful_binds_persec', label: '成功绑定', color: '#2f6bff', unit: 'cps' },
        { metric: 'ad_ldap_searches_persec', label: '搜索', color: '#13c2c2', unit: 'cps' },
        { metric: 'ad_ldap_writes_persec', label: '写入', color: '#722ed1', unit: 'cps' },
        { metric: 'ad_ldap_new_connections_persec', label: '新连接', color: '#597ef7', unit: 'cps' },
        { metric: 'ad_ldap_bind_time', label: '绑定耗时', color: '#ff8a1f', unit: 'ms' },
      ],
    },
    {
      title: 'NTDS 目录服务',
      subtitle: '读 / 搜 / 写 / 线程 / Notify 队列',
      metric: 'ad_ds_directory_reads_persec',
      guide: [{ label: 'NTDS', detail: 'Directory Services 读写吞吐与 notify 队列，反映目录引擎负载。' }],
      series: [
        { metric: 'ad_ds_directory_reads_persec', label: '目录读取', color: '#2f6bff', unit: 'cps' },
        { metric: 'ad_ds_directory_searches_persec', label: '目录搜索', color: '#13c2c2', unit: 'cps' },
        { metric: 'ad_ds_directory_writes_persec', label: '目录写入', color: '#722ed1', unit: 'cps' },
        { metric: 'ad_ds_threads_in_use', label: '目录线程', color: '#8a5cff', unit: 'counts' },
        { metric: 'ad_ds_notify_queue_size', label: 'Notify 队列', color: '#faad14', unit: 'counts' },
      ],
    },
    {
      title: '复制健康',
      subtitle: '积压 / 全量同步剩余',
      metric: 'ad_dra_pending_replication_operations',
      guide: [{ label: '复制', detail: '待复制操作与同步积压；全量同步剩余对象非零表示仍在 catch-up。' }],
      series: [
        { metric: 'ad_dra_pending_replication_operations', label: '待复制操作', color: '#ff4d4f', unit: 'counts' },
        { metric: 'ad_dra_pending_replication_synchronizations', label: '待同步', color: '#ff8a1f', unit: 'counts' },
        { metric: 'ad_dra_inbound_full_sync_objects_remaining', label: '全量同步剩余', color: '#faad14', unit: 'counts' },
      ],
    },
    {
      title: '复制吞吐',
      subtitle: '入站 / 出站字节速率',
      metric: 'ad_dra_inbound_bytes_total_persec',
      guide: [{ label: '复制带宽', detail: '域间复制字节速率，用于观察复制风暴或链路压力。' }],
      series: [
        { metric: 'ad_dra_inbound_bytes_total_persec', label: '入站', color: '#27c274', unit: 'byteps' },
        { metric: 'ad_dra_outbound_bytes_total_persec', label: '出站', color: '#2f6bff', unit: 'byteps' },
      ],
    },
    {
      title: '会话与 ATQ',
      subtitle: '客户端会话 / 排队 / 延迟',
      metric: 'ad_ldap_client_sessions',
      guide: [{ label: 'ATQ', detail: '客户端会话与 ATQ 排队延迟，定位域控内部请求排队瓶颈。' }],
      series: [
        { metric: 'ad_ldap_client_sessions', label: '客户端会话', color: '#27c274', unit: 'counts' },
        { metric: 'ad_atq_outstanding_queued_requests', label: 'ATQ 排队', color: '#ff8a1f', unit: 'counts' },
        { metric: 'ad_atq_estimated_queue_delay', label: 'ATQ 延迟', color: '#ff4d4f', unit: 'ms' },
      ],
    },
    {
      title: 'LDAP 端点延迟',
      subtitle: 'LDAP / LDAPS 探测 RTT',
      metric: 'ad_ldap_probe_response_time',
      guide: [{ label: '探测 RTT', detail: '本地 LDAP/LDAPS TCP 探测往返时延，类似 synthetic 监控的 latency SLO。' }],
      series: [
        { metric: 'ad_ldap_probe_response_time', label: 'LDAP', color: '#ff8a1f', unit: 'ms' },
        { metric: 'ad_ldaps_probe_response_time', label: 'LDAPS', color: '#8a5cff', unit: 'ms' },
      ],
    },
  ],
  ringPanels: [
    {
      title: 'LDAP 操作构成',
      subtitle: '绑定 / 搜索 / 写入',
      centerMetric: 'ad_ldap_successful_binds_persec',
      centerCaption: '成功绑定/s',
      centerUnit: 'cps',
      guide: [{ label: '操作占比', detail: '按当前速率拆分 LDAP 绑定、搜索与写入，识别目录访问模式。' }],
      segments: [
        { label: '成功绑定', metric: 'ad_ldap_successful_binds_persec', color: '#2f6bff', unit: 'cps' },
        { label: '搜索', metric: 'ad_ldap_searches_persec', color: '#13c2c2', unit: 'cps' },
        { label: '写入', metric: 'ad_ldap_writes_persec', color: '#722ed1', unit: 'cps' },
      ],
    },
  ],
  barPanels: [],
  statusPanels: [],
  details: [],
};
