import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  ALL_OBJECT_TYPES,
  CAPABILITY_METRICS,
  type CapabilityKey,
  type ObjectType
} from '../src/app/monitor/dashboards/shared/capability-matrix-core';

// 命令从 web/ 执行；后端插件根目录在仓库 server/ 下。
const PLUGIN_ROOT = path.resolve(process.cwd(), '../server/apps/monitor/support-files/plugins/Telegraf');
const OUT_FILE = path.resolve(process.cwd(), 'src/app/monitor/dashboards/shared/capability-matrix.generated.ts');

function collectMetricNames(file: string): Set<string> {
  const json = JSON.parse(fs.readFileSync(file, 'utf8'));
  const names = new Set<string>();
  for (const metric of json.metrics || []) {
    if (metric && typeof metric.name === 'string') {
      names.add(metric.name);
    }
  }
  // supplementary_indicators 是指标名字符串数组。
  for (const indicator of json.supplementary_indicators || []) {
    if (typeof indicator === 'string') {
      names.add(indicator);
    }
  }
  return names;
}

function deriveCapabilities(objectType: ObjectType, names: Set<string>): CapabilityKey[] {
  const groups = CAPABILITY_METRICS[objectType];
  const caps: CapabilityKey[] = [];
  // 按 CAPABILITY_METRICS 的 key 顺序输出，保证生成结果稳定、diff 干净。
  for (const key of Object.keys(groups) as CapabilityKey[]) {
    if (groups[key].some((metricName) => names.has(metricName))) {
      caps.push(key);
    }
  }
  return caps;
}

// 品牌插件是基于通用 snmp 底座的 child 配置（如 cisco.child.toml.j2），其 metrics.json 只声明
// 厂商增量，不重复声明底座已采集的 sysUpTime / IF-MIB 接口计数。因此每个品牌能力需并入
// 通用 snmp/<object> 底座（uptime + traffic 等通用能力），否则会漏掉这些能力。
const FLOOR: Record<ObjectType, Set<CapabilityKey>> = {
  switch: new Set(),
  router: new Set(),
  firewall: new Set(),
  loadbalance: new Set()
};
for (const objectType of ALL_OBJECT_TYPES) {
  const floorFile = path.join(PLUGIN_ROOT, 'snmp', objectType, 'metrics.json');
  if (fs.existsSync(floorFile)) {
    FLOOR[objectType] = new Set(deriveCapabilities(objectType, collectMetricNames(floorFile)));
  }
}

// 并入底座并按 CAPABILITY_METRICS 的 key 顺序输出，保证 diff 稳定。
function withFloor(objectType: ObjectType, caps: CapabilityKey[]): CapabilityKey[] {
  const set = new Set<CapabilityKey>([...caps, ...FLOOR[objectType]]);
  return (Object.keys(CAPABILITY_METRICS[objectType]) as CapabilityKey[]).filter((key) => set.has(key));
}

const matrix: Record<ObjectType, { collectType: string; capabilities: CapabilityKey[] }[]> = {
  switch: [],
  router: [],
  firewall: [],
  loadbalance: []
};

// 扁平布局：所有 SNMP 插件目录都在 Telegraf/snmp/ 下一级——
// 通用档 snmp/<object>/（无显式 collect_type → 视为 'snmp'），厂商 snmp/<brand>_<object>/
// （metrics.json 显式声明 collect_type=snmp_<brand>）。objectType 由 metrics.json 的 name 推导。
const SNMP_ROOT = path.join(PLUGIN_ROOT, 'snmp');
for (const entry of fs.readdirSync(SNMP_ROOT).sort()) {
  const file = path.join(SNMP_ROOT, entry, 'metrics.json');
  if (!fs.existsSync(file)) {
    continue;
  }
  const json = JSON.parse(fs.readFileSync(file, 'utf8'));
  const objectType = String(json.name || '').toLowerCase();
  if (!(ALL_OBJECT_TYPES as string[]).includes(objectType)) {
    continue; // 仅处理 switch/router/firewall/loadbalance 四类
  }
  const ot = objectType as ObjectType;
  const collectType: string = json.collect_type || 'snmp';
  const capabilities = withFloor(ot, deriveCapabilities(ot, collectMetricNames(file)));
  if (capabilities.length) {
    matrix[ot].push({ collectType, capabilities });
  }
}

// 按 collectType 排序，保持与旧产物一致的顺序、diff 干净。
for (const ot of ALL_OBJECT_TYPES) {
  matrix[ot].sort((a, b) => a.collectType.localeCompare(b.collectType));
}

const banner =
  '// AUTO-GENERATED by web/scripts/generate-capability-matrix.ts — DO NOT EDIT BY HAND.\n' +
  '// Source of truth: server/apps/monitor/support-files/plugins/Telegraf/snmp/<object>_<brand>/metrics.json\n' +
  '// Regenerate: pnpm gen:capability-matrix\n\n';

const content =
  banner +
  "import type { CapabilityMatrix } from './capability-matrix-core';\n\n" +
  `export const CAPABILITY_MATRIX: CapabilityMatrix = ${JSON.stringify(matrix, null, 2)};\n`;

fs.writeFileSync(OUT_FILE, content);
console.log(`generated ${OUT_FILE}`);
console.log(
  `switch=${matrix.switch.length} router=${matrix.router.length} firewall=${matrix.firewall.length} loadbalance=${matrix.loadbalance.length}`
);
