import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { excelCellToText } from '../src/app/system-manager/utils/excelCellText';

const root = path.resolve(import.meta.dirname, '..');
const page = fs.readFileSync(path.join(root, 'src/app/system-manager/(pages)/user/structure/page.tsx'), 'utf8');
const api = fs.readFileSync(path.join(root, 'src/app/system-manager/api/user/index.ts'), 'utf8');
const modal = fs.readFileSync(path.join(root, 'src/app/system-manager/(pages)/user/structure/userImportModal.tsx'), 'utf8');

assert.match(page, /UserImportModal/, '组织架构用户列表应接入导入弹窗');
assert.match(page, /<UserImportModal[\s\S]*treeData=\{treeData\}/, '导入弹窗应使用组织架构页的组织树，而不是登录态 groupTree');
assert.match(page, /requiredPermissions=\{\['Add User'\]\}/, '导入入口应受新增用户权限保护');
assert.match(api, /importUsers/, '用户 API 应提供批量导入方法');
assert.match(api, /import_users/, '用户 API 应调用批量导入接口');
assert.match(modal, /ZONEINFO_OPTIONS/, '导入模板应使用平台支持的时区选项');
assert.match(modal, /LOCALE_OPTIONS/, '导入模板应使用平台支持的语言选项');
assert.match(modal, /dataValidation/, '导入模板的时区和语言应为 Excel 下拉选项');
assert.match(modal, /numFmt = '@'/, '用户名/姓名/邮箱/手机号列应设为文本，降低 Excel 自动超链接');
assert.match(modal, /formula: '"zhangsan@example.com"'/, '示例邮箱应写成文本公式，避免打开模板时变成 mailto 链接');
assert.match(modal, /excelCellToText/, '解析 Excel 时应取出超链接/公式单元格中的文本');
assert.equal(excelCellToText('example@example.com'), 'example@example.com');
assert.equal(excelCellToText({ text: 'example@example.com', hyperlink: 'mailto:example@example.com' }), 'example@example.com');
assert.equal(excelCellToText({ formula: '"example@example.com"', result: 'example@example.com' }), 'example@example.com');
assert.equal(excelCellToText({ hyperlink: 'mailto:example@example.com?subject=hi' }), 'example@example.com');
assert.equal(excelCellToText({ richText: [{ text: 'example' }, { text: '@example.com' }] }), 'example@example.com');
assert.equal(excelCellToText({}), '');
assert.match(modal, /system\.user\.import\.fileHint/, '上传区应明确文件格式与大小限制');
assert.match(modal, /<Button type="link"[\s\S]*system\.user\.import\.downloadTemplate/, '下载模板应以内联链接形式呈现');
assert.match(modal, /<GroupTreeSelect[\s\S]*multiple=\{false\}/, '目标组织应复用项目的单选组织树组件');
assert.match(modal, /<GroupTreeSelect[\s\S]*treeData=\{groupTreeSelectData\}/, '目标组织选择应使用页面传入的组织树');
assert.match(modal, /toGroupTreeSelectNodes\(treeData\)/, '页面组织树应转换成选择器可用的节点');
assert.match(modal, /data\.failed_count === 0/, '全量成功时应走完成反馈分支');
assert.match(modal, /system\.user\.import\.allSuccess/, '全量成功应使用全局成功提示');
assert.match(modal, /setOpen\(false\);[\s\S]*onSuccess\(\);/, '全量成功后应关闭弹窗并刷新列表');
assert.match(modal, /failureGroups/, '失败结果应按原因聚合');
assert.match(modal, /view === 'result'/, '部分或全部失败应进入独立导入结果态');
assert.match(modal, /system\.user\.import\.noneImported/, '全部失败应使用“未导入任何用户”类业务结论');
assert.match(modal, /CloseCircleFilled/, '结果态应使用状态图标区分全部失败与部分成功');
assert.match(modal, /--color-fail/, '全部失败状态应使用失败语义色');
assert.match(modal, /system\.user\.import\.failedCountLabel/, '全部失败应在状态行给出一次失败计数');
assert.match(modal, /system\.user\.import\.partialHint/, '部分成功应把成功/失败计数写在结论下一行，而不是再铺一层指标');
assert.match(modal, /group\.message/, '失败原因应作为分组标题直接展示');
assert.match(modal, /system\.user\.import\.failureRowNo/, '失败明细应直接展示行号与用户名');
assert.match(modal, /system\.user\.import\.failureRow/, '复制失败名单应使用可带走的一行格式');
assert.match(modal, /system\.user\.import\.copyFailures/, '结果态应提供复制失败名单');
assert.match(modal, /system\.user\.import\.changeFile/, '结果态应提供更换文件');
assert.match(modal, /type="primary"[\s\S]*handleClose/, '冲突结果的主按钮应是关闭，而不是再传一次');
assert.match(modal, /common\.close/, '结果态应提供关闭');
assert.match(modal, /sticky top-0/, '状态行应在滚动名单时保持可见');
assert.match(modal, /<h3/, '失败原因应使用标题语义');
assert.doesNotMatch(modal, /<Tag/, '失败原因不应再做成 Tag 芯片');
assert.doesNotMatch(modal, /Collapse/, '短列表失败明细不应再藏进 Collapse');
assert.doesNotMatch(modal, /system\.user\.import\.viewFailures/, '失败明细应默认可见，而不是“查看 N 条”');
assert.doesNotMatch(modal, /system\.user\.import\.noneImportedHint/, '全部失败不应再重复“共 N 条均未导入”');
assert.doesNotMatch(modal, /system\.user\.import\.totalCountLabel/, '全部失败不应再铺“共 N | 失败 N”计数行');
assert.doesNotMatch(modal, /system\.user\.import\.reupload/, '主路径不应再使用“重新上传”文案');
assert.doesNotMatch(modal, /color-mix/, '结果态不应再使用大块失败色洗底');
assert.doesNotMatch(modal, /type="warning"/, '结果态不应再使用黄色 Alert 叠在表单上');
assert.doesNotMatch(modal, /okText="导入"/, '结果态不应继续展示原导入按钮');
