server_name: apm-contract-nats
http_port: 8222

jetstream {
  store_dir: /data/jetstream
  max_memory_store: 256MB
  max_file_store: 1GB
}

authorization {
  users: [
    {
      user: $NATS_ADMIN_USERNAME
      password: $NATS_ADMIN_PASSWORD
      permissions: {publish: ">", subscribe: ">"}
    },
    {
      user: $NATS_REGION_USERNAME
      password: $NATS_REGION_PASSWORD
      permissions: {
        publish: $NATS_REGION_PUBLISH_SUBJECT,
        subscribe: "_INBOX.>"
      }
    },
    {
      user: $NATS_SYSTEM_USERNAME
      password: $NATS_SYSTEM_PASSWORD
      permissions: {
        publish: [
          "$JS.API.STREAM.INFO.APM_TRACES",
          "$JS.API.CONSUMER.INFO.APM_TRACES.*",
          "$JS.API.CONSUMER.MSG.NEXT.APM_TRACES.*",
          "$JS.ACK.APM_TRACES.>"
        ],
        subscribe: "_INBOX.>"
      }
    }
  ]
}
