# Generated by Django 4.2.27 on 2026-07-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    - interval: 业务要求采集频率默认 60s(commit eb1296905)
    - algorithm verbose_name: 顺带修 d38cada17 遗留的 metadata drift,DB schema 无变更
    """

    dependencies = [
        ('monitor', '0044_rename_monitor_object_type_os_to_host_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorinstance',
            name='interval',
            field=models.IntegerField(default=60, verbose_name='监控实例采集间隔(s)'),
        ),
        migrations.AlterField(
            model_name='monitorpolicy',
            name='algorithm',
            field=models.CharField(max_length=50, verbose_name='周期聚合算法'),
        ),
    ]
