# Generated by Django 4.2.27 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0045_alter_monitorinstance_interval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="view_query",
            field=models.TextField(blank=True, default="", verbose_name="指标卡视图查询语句"),
        ),
    ]
