# Generated by Django 4.2.27 on 2026-07-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0045_alter_monitorinstance_interval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorpolicy",
            name="threshold_unit",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="告警阈值单位",
            ),
        ),
    ]
