export const ZONEINFO_OPTIONS = [
  { value: 'Pacific/Honolulu', label: 'system.zoneinfo.PacificHonolulu' },
  { value: 'America/Anchorage', label: 'system.zoneinfo.AmericaAnchorage' },
  { value: 'America/Los_Angeles', label: 'system.zoneinfo.AmericaLosAngeles' },
  { value: 'America/Denver', label: 'system.zoneinfo.AmericaDenver' },
  { value: 'America/Chicago', label: 'system.zoneinfo.AmericaChicago' },
  { value: 'America/New_York', label: 'system.zoneinfo.AmericaNewYork' },
  { value: 'America/Caracas', label: 'system.zoneinfo.AmericaCaracas' },
  { value: 'America/Halifax', label: 'system.zoneinfo.AmericaHalifax' },
  { value: 'America/Sao_Paulo', label: 'system.zoneinfo.AmericaSaoPaulo' },
  { value: 'Atlantic/South_Georgia', label: 'system.zoneinfo.AtlanticSouthGeorgia' },
  { value: 'Atlantic/Azores', label: 'system.zoneinfo.AtlanticAzores' },
  { value: 'Europe/London', label: 'system.zoneinfo.EuropeLondon' },
  { value: 'Africa/Lagos', label: 'system.zoneinfo.AfricaLagos' },
  { value: 'Europe/Berlin', label: 'system.zoneinfo.EuropeBerlin' },
  { value: 'Europe/Athens', label: 'system.zoneinfo.EuropeAthens' },
  { value: 'Asia/Jerusalem', label: 'system.zoneinfo.AsiaJerusalem' },
  { value: 'Europe/Istanbul', label: 'system.zoneinfo.EuropeIstanbul' },
  { value: 'Asia/Dubai', label: 'system.zoneinfo.AsiaDubai' },
  { value: 'Indian/Maldives', label: 'system.zoneinfo.IndianMaldives' },
  { value: 'Asia/Yekaterinburg', label: 'system.zoneinfo.AsiaYekaterinburg' },
  { value: 'Asia/Kolkata', label: 'system.zoneinfo.AsiaKolkata' },
  { value: 'Asia/Kathmandu', label: 'system.zoneinfo.AsiaKathmandu' },
  { value: 'Asia/Almaty', label: 'system.zoneinfo.AsiaAlmaty' },
  { value: 'Asia/Bangkok', label: 'system.zoneinfo.AsiaBangkok' },
  { value: 'Asia/Shanghai', label: 'system.zoneinfo.AsiaShanghai' },
  { value: 'Asia/Tokyo', label: 'system.zoneinfo.AsiaTokyo' },
  { value: 'Australia/Sydney', label: 'system.zoneinfo.AustraliaSydney' },
  { value: 'Pacific/Noumea', label: 'system.zoneinfo.PacificNoumea' },
  { value: 'Pacific/Auckland', label: 'system.zoneinfo.PacificAuckland' },
];

export const LOCALE_OPTIONS = [
  { value: 'en', label: 'system.common.english' },
  { value: 'zh-Hans', label: 'system.common.chinese' },
];
