// AUTO-GENERATED by web/scripts/generate-capability-matrix.ts — DO NOT EDIT BY HAND.
// Source of truth: server/apps/monitor/support-files/plugins/Telegraf/snmp/<object>_<brand>/metrics.json
// Regenerate: pnpm gen:capability-matrix

import type { CapabilityMatrix } from './capability-matrix-core';

export const CAPABILITY_MATRIX: CapabilityMatrix = {
  "switch": [
    {
      "collectType": "snmp",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_3com",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_alcatel",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_alliedtelesis",
      "capabilities": [
        "uptime",
        "cpu",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_arista",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_aruba",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_brocade",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cisco",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cumulus",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_datacom",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_dcn",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_dellforce",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_dellos10",
      "capabilities": [
        "uptime",
        "cpu",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_dlink",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_edgecore",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_eltex",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_enterasys",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_extreme",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_fiberhome",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_fortiswitch",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_fs",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_garretcom",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_h3c",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_hirschmann",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_hphpn",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_huawei",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_juniper",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_lenovocnos",
      "capabilities": [
        "uptime",
        "cpu",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_mellanox",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_microsens",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_mikrotik",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_moxa",
      "capabilities": [
        "uptime",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_netgear",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_netonix",
      "capabilities": [
        "uptime",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_omniswitch",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_parks",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_planet",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_pluribus",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_qtech",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_ruggedcom",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_ruijie",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_scalance",
      "capabilities": [
        "uptime",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_snr",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "fan",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_tplink",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_ubiquiti",
      "capabilities": [
        "uptime",
        "memory",
        "temperature",
        "fan",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_westermo",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_yamaha",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_zte",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_zyxel",
      "capabilities": [
        "uptime",
        "cpu",
        "temperature",
        "traffic"
      ]
    }
  ],
  "router": [
    {
      "collectType": "snmp",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_adtran",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_bintec",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_cradlepoint",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_digi",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_draytek",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_huawei_ar",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_juniper_mx",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_lancom",
      "capabilities": [
        "uptime",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_nec",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_oneaccess",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_teldat",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_teltonika",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_versa",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_viprinet",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_vyatta",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_yamaha",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "traffic"
      ]
    }
  ],
  "firewall": [
    {
      "collectType": "snmp",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_checkpoint",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_clavister",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_forcepoint",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_fortinet",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_genua",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_hillstone",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "temperature",
        "psu",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_kerio",
      "capabilities": [
        "uptime",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_opnsense",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_paloalto",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_pfsense",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_sangfor",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_screenos",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_sonicwall",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_sophos",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_stormshield",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_watchguard",
      "capabilities": [
        "uptime",
        "cpu",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_zorp",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    }
  ],
  "loadbalance": [
    {
      "collectType": "snmp",
      "capabilities": [
        "uptime",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_a10",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_alteon",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic"
      ]
    },
    {
      "collectType": "snmp_f5",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_fortiadc",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_kemp",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    },
    {
      "collectType": "snmp_netscaler",
      "capabilities": [
        "uptime",
        "cpu",
        "memory",
        "traffic",
        "session"
      ]
    }
  ]
};
