# Generated by Django 4.2.22 on 2026-01-08 08:56

import apps.core.fields.s3_json_field
from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0035_alter_timeseriespredictdatasetrelease_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetectionDatasetRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(help_text='数据集发布版本的名称', max_length=100, verbose_name='发布版本名称')),
                ('description', models.TextField(blank=True, help_text='发布版本的详细描述', null=True, verbose_name='版本描述')),
                ('version', models.CharField(help_text='数据集版本号，如 v1.0.0', max_length=50, verbose_name='版本号')),
                ('dataset_file', models.FileField(help_text='存储在MinIO中的数据集ZIP压缩包', storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='数据集压缩包')),
                ('file_size', models.BigIntegerField(default=0, help_text='压缩包文件大小（字节）', verbose_name='文件大小')),
                ('status', models.CharField(choices=[('pending', '待发布'), ('published', '已发布'), ('failed', '发布失败'), ('archived', '归档')], default='pending', help_text='数据集发布状态', max_length=20, verbose_name='发布状态')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='数据集的统计信息和质量指标，不包含训练配置', verbose_name='数据集元信息')),
                ('dataset', models.ForeignKey(help_text='关联的数据集', on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='mlops.anomalydetectiondataset', verbose_name='数据集')),
            ],
            options={
                'verbose_name': '异常检测数据集发布版本',
                'verbose_name_plural': '异常检测数据集发布版本',
                'ordering': ['-created_at'],
                'unique_together': {('dataset', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LogClusteringDatasetRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(help_text='数据集发布版本的名称', max_length=100, verbose_name='发布版本名称')),
                ('description', models.TextField(blank=True, help_text='发布版本的详细描述', null=True, verbose_name='版本描述')),
                ('version', models.CharField(help_text='数据集版本号，如 v1.0.0', max_length=50, verbose_name='版本号')),
                ('dataset_file', models.FileField(help_text='存储在MinIO中的数据集ZIP压缩包', storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='数据集压缩包')),
                ('file_size', models.BigIntegerField(default=0, help_text='压缩包文件大小（字节）', verbose_name='文件大小')),
                ('status', models.CharField(choices=[('pending', '待发布'), ('published', '已发布'), ('failed', '发布失败'), ('archived', '归档')], default='pending', help_text='数据集发布状态', max_length=20, verbose_name='发布状态')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='数据集的统计信息和质量指标，不包含训练配置', verbose_name='数据集元信息')),
                ('dataset', models.ForeignKey(help_text='关联的数据集', on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='mlops.logclusteringdataset', verbose_name='数据集')),
            ],
            options={
                'verbose_name': '日志聚类数据集发布版本',
                'verbose_name_plural': '日志聚类数据集发布版本',
                'ordering': ['-created_at'],
                'unique_together': {('dataset', 'version')},
            },
        ),
        migrations.RemoveField(
            model_name='anomalydetectionserving',
            name='anomaly_threshold',
        ),
        migrations.RemoveField(
            model_name='anomalydetectiontraindata',
            name='anomaly_point_count',
        ),
        migrations.RemoveField(
            model_name='anomalydetectiontrainjob',
            name='test_data_id',
        ),
        migrations.RemoveField(
            model_name='anomalydetectiontrainjob',
            name='train_data_id',
        ),
        migrations.RemoveField(
            model_name='anomalydetectiontrainjob',
            name='val_data_id',
        ),
        migrations.RemoveField(
            model_name='logclusteringserving',
            name='api_endpoint',
        ),
        migrations.RemoveField(
            model_name='logclusteringserving',
            name='max_requests_per_minute',
        ),
        migrations.RemoveField(
            model_name='logclusteringserving',
            name='supported_log_formats',
        ),
        migrations.RemoveField(
            model_name='logclusteringtraindata',
            name='log_count',
        ),
        migrations.RemoveField(
            model_name='logclusteringtraindata',
            name='log_source',
        ),
        migrations.RemoveField(
            model_name='logclusteringtrainjob',
            name='cluster_count',
        ),
        migrations.RemoveField(
            model_name='logclusteringtrainjob',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='logclusteringtrainjob',
            name='min_samples',
        ),
        migrations.RemoveField(
            model_name='logclusteringtrainjob',
            name='test_data_id',
        ),
        migrations.RemoveField(
            model_name='logclusteringtrainjob',
            name='train_data_id',
        ),
        migrations.RemoveField(
            model_name='logclusteringtrainjob',
            name='val_data_id',
        ),
        migrations.RemoveField(
            model_name='timeseriespredicttrainjob',
            name='test_data_id',
        ),
        migrations.RemoveField(
            model_name='timeseriespredicttrainjob',
            name='train_data_id',
        ),
        migrations.RemoveField(
            model_name='timeseriespredicttrainjob',
            name='val_data_id',
        ),
        migrations.AddField(
            model_name='anomalydetectionserving',
            name='container_info',
            field=models.JSONField(blank=True, default=dict, help_text='webhookd 返回的容器实时状态，格式：{status, id, state, port, detail, ...}', verbose_name='容器状态信息'),
        ),
        migrations.AddField(
            model_name='anomalydetectionserving',
            name='port',
            field=models.IntegerField(blank=True, help_text='用户指定端口，为空则由 docker 自动分配。实际端口以 container_info.port 为准', null=True, verbose_name='服务端口'),
        ),
        migrations.AddField(
            model_name='anomalydetectiontrainjob',
            name='config_url',
            field=models.FileField(blank=True, help_text='MinIO 中的 JSON 文件备份', null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='配置文件备份'),
        ),
        migrations.AddField(
            model_name='logclusteringserving',
            name='container_info',
            field=models.JSONField(blank=True, default=dict, help_text='webhookd 返回的容器实时状态，格式：{status, id, state, port, detail, ...}', verbose_name='容器状态信息'),
        ),
        migrations.AddField(
            model_name='logclusteringserving',
            name='port',
            field=models.IntegerField(blank=True, help_text='用户指定端口，为空则由 docker 自动分配。实际端口以 container_info.port 为准', null=True, verbose_name='服务端口'),
        ),
        migrations.AddField(
            model_name='logclusteringtrainjob',
            name='config_url',
            field=models.FileField(blank=True, help_text='MinIO 中的 JSON 文件备份', null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='配置文件备份'),
        ),
        migrations.AddField(
            model_name='timeseriespredictserving',
            name='container_info',
            field=models.JSONField(blank=True, default=dict, help_text='webhookd 返回的容器实时状态，格式：{status, id, state, port, detail, ...}', verbose_name='容器状态信息'),
        ),
        migrations.AddField(
            model_name='timeseriespredictserving',
            name='port',
            field=models.IntegerField(blank=True, help_text='用户指定端口，为空则由 docker 自动分配。实际端口以 container_info.port 为准', null=True, verbose_name='服务端口'),
        ),
        migrations.AddField(
            model_name='timeseriespredicttrainjob',
            name='config_url',
            field=models.FileField(blank=True, help_text='MinIO 中的 JSON 文件备份', null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='配置文件备份'),
        ),
        migrations.AddField(
            model_name='timeseriespredicttrainjob',
            name='dataset_version',
            field=models.ForeignKey(blank=True, help_text='关联的时间序列预测数据集版本', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_jobs', to='mlops.timeseriespredictdatasetrelease', verbose_name='数据集版本'),
        ),
        migrations.AlterField(
            model_name='anomalydetectionserving',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='用户意图：是否希望服务运行', max_length=20, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='anomalydetectiontraindata',
            name='metadata',
            field=apps.core.fields.s3_json_field.S3JSONField(blank=True, bucket_name='munchkin-public', compressed=True, help_text='存储在MinIO中的训练数据元信息文件路径', max_length=500, null=True, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='anomalydetectiontraindata',
            name='train_data',
            field=models.FileField(blank=True, help_text='存储在MinIO中的JSON训练数据文件', null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='训练数据'),
        ),
        migrations.AlterField(
            model_name='anomalydetectiontrainjob',
            name='algorithm',
            field=models.CharField(choices=[('RandomForest', 'RandomForest'), ('ECOD', 'ECOD')], help_text='使用的异常检测算法模型', max_length=50, verbose_name='算法模型'),
        ),
        migrations.AlterField(
            model_name='anomalydetectiontrainjob',
            name='hyperopt_config',
            field=models.JSONField(blank=True, default=dict, help_text='存储在数据库中，供API快速返回', verbose_name='训练配置'),
        ),
        migrations.AlterField(
            model_name='logclusteringserving',
            name='description',
            field=models.TextField(blank=True, help_text='服务的详细描述', null=True, verbose_name='服务描述'),
        ),
        migrations.AlterField(
            model_name='logclusteringserving',
            name='name',
            field=models.CharField(help_text='服务的名称', max_length=100, verbose_name='服务名称'),
        ),
        migrations.AlterField(
            model_name='logclusteringserving',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='用户意图：是否希望服务运行', max_length=20, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='logclusteringtraindata',
            name='metadata',
            field=apps.core.fields.s3_json_field.S3JSONField(blank=True, bucket_name='munchkin-public', compressed=True, help_text='存储在MinIO中的训练数据元信息文件路径', max_length=500, null=True, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='logclusteringtraindata',
            name='train_data',
            field=models.FileField(blank=True, help_text='存储在MinIO中的日志数据文件', null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='训练数据'),
        ),
        migrations.AlterField(
            model_name='logclusteringtrainjob',
            name='algorithm',
            field=models.CharField(choices=[('KMeans', 'K-Means'), ('DBSCAN', 'DBSCAN'), ('AgglomerativeClustering', '层次聚类'), ('Drain', 'Drain'), ('LogCluster', 'LogCluster'), ('Spell', 'Spell')], help_text='使用的日志聚类算法模型', max_length=50, verbose_name='算法模型'),
        ),
        migrations.AlterField(
            model_name='logclusteringtrainjob',
            name='hyperopt_config',
            field=models.JSONField(blank=True, default=dict, help_text='存储在数据库中，供API快速返回', verbose_name='训练配置'),
        ),
        migrations.AlterField(
            model_name='timeseriespredictserving',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='用户意图：是否希望服务运行', max_length=20, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='timeseriespredicttrainjob',
            name='algorithm',
            field=models.CharField(choices=[('Prophet', 'Prophet'), ('GradientBoosting', 'GradientBoosting'), ('RandomForest', 'RandomForest'), ('Sktime', 'Sktime')], help_text='使用的时间序列预测算法模型', max_length=50, verbose_name='算法模型'),
        ),
        migrations.AlterField(
            model_name='timeseriespredicttrainjob',
            name='hyperopt_config',
            field=models.JSONField(blank=True, default=dict, help_text='存储在数据库中，供API快速返回', verbose_name='训练配置'),
        ),
        migrations.DeleteModel(
            name='AnomalyDetectionTrainHistory',
        ),
        migrations.DeleteModel(
            name='LogClusteringTrainHistory',
        ),
        migrations.DeleteModel(
            name='TimeSeriesPredictTrainHistory',
        ),
        migrations.AddField(
            model_name='anomalydetectiontrainjob',
            name='dataset_version',
            field=models.ForeignKey(blank=True, help_text='关联的异常检测数据集版本', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_jobs', to='mlops.anomalydetectiondatasetrelease', verbose_name='数据集版本'),
        ),
        migrations.AddField(
            model_name='logclusteringtrainjob',
            name='dataset_version',
            field=models.ForeignKey(blank=True, help_text='关联的日志聚类数据集版本', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_jobs', to='mlops.logclusteringdatasetrelease', verbose_name='数据集版本'),
        ),
    ]
