# Generated by Django 4.2.27 on 2026-07-28 09:01

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlops", "0045_anomalydetectiondataset_team_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainDataFileReferenceGuard",
            fields=[
                (
                    "lock_key",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deleting", "Deleting"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mlops_train_data_file_reference_guard",
            },
        ),
        migrations.AlterField(
            model_name="anomalydetectiontraindata",
            name="train_data",
            field=models.FileField(
                blank=True,
                db_index=True,
                help_text="存储在MinIO中的JSON训练数据文件",
                null=True,
                storage=django_minio_backend.models.MinioBackend(
                    bucket_name="munchkin-public"
                ),
                upload_to=django_minio_backend.models.iso_date_prefix,
                verbose_name="训练数据",
            ),
        ),
        migrations.AlterField(
            model_name="classificationtraindata",
            name="train_data",
            field=models.FileField(
                blank=True,
                db_index=True,
                help_text="存储在MinIO中的CSV训练数据文件",
                null=True,
                storage=django_minio_backend.models.MinioBackend(
                    bucket_name="munchkin-public"
                ),
                upload_to=django_minio_backend.models.iso_date_prefix,
                verbose_name="训练数据",
            ),
        ),
        migrations.AlterField(
            model_name="imageclassificationtraindata",
            name="train_data",
            field=models.FileField(
                blank=True,
                db_index=True,
                help_text="存储在MinIO中的图片压缩包文件（ZIP格式）",
                null=True,
                storage=django_minio_backend.models.MinioBackend(
                    bucket_name="munchkin-public"
                ),
                upload_to=django_minio_backend.models.iso_date_prefix,
                verbose_name="训练数据",
            ),
        ),
        migrations.AlterField(
            model_name="logclusteringtraindata",
            name="train_data",
            field=models.FileField(
                blank=True,
                db_index=True,
                help_text="存储在MinIO中的日志数据文件",
                null=True,
                storage=django_minio_backend.models.MinioBackend(
                    bucket_name="munchkin-public"
                ),
                upload_to=django_minio_backend.models.iso_date_prefix,
                verbose_name="训练数据",
            ),
        ),
        migrations.AlterField(
            model_name="objectdetectiontraindata",
            name="train_data",
            field=models.FileField(
                blank=True,
                db_index=True,
                help_text=(
                    "存储在 MinIO 中的 YOLO 格式 ZIP 压缩包"
                    "（images/ + labels/ + classes.txt）"
                ),
                null=True,
                storage=django_minio_backend.models.MinioBackend(
                    bucket_name="munchkin-public"
                ),
                upload_to=django_minio_backend.models.iso_date_prefix,
                verbose_name="训练数据",
            ),
        ),
        migrations.AlterField(
            model_name="timeseriespredicttraindata",
            name="train_data",
            field=models.FileField(
                blank=True,
                db_index=True,
                help_text="存储在MinIO中的CSV训练数据文件",
                null=True,
                storage=django_minio_backend.models.MinioBackend(
                    bucket_name="munchkin-public"
                ),
                upload_to=django_minio_backend.models.iso_date_prefix,
                verbose_name="训练数据",
            ),
        ),
    ]
