# Generated by Django 4.2.27 on 2026-07-28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlops", "0046_traindatafilereferenceguard_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSeriesRuntimeGuard",
            fields=[
                (
                    "serving_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mlops_timeseries_runtime_guard",
            },
        ),
        migrations.CreateModel(
            name="TimeSeriesRuntimeCleanupIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Created Time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Updated Time",
                    ),
                ),
                (
                    "cleanup_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("container_id", models.CharField(max_length=255)),
                ("serving_id", models.BigIntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待清理"),
                            ("completed", "已清理"),
                            ("owned", "已被业务记录接管"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_retry_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "mlops_timeseries_runtime_cleanup_intent",
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="mlops_ts_cleanup_retry_idx",
                    )
                ],
            },
        ),
    ]
