# Generated by Django 4.2.27 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mlops", "0047_timeseriesruntimeguard_and_cleanup_intent"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetReleaseExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Created Time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Updated Time",
                    ),
                ),
                ("release_type", models.CharField(max_length=100)),
                ("release_id", models.PositiveBigIntegerField()),
                (
                    "owner_token",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("lease_expires_at", models.DateTimeField()),
                ("attempt", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "mlops_dataset_release_execution",
                "indexes": [
                    models.Index(
                        fields=["release_type", "lease_expires_at"],
                        name="mlops_release_lease_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("release_type", "release_id"),
                        name="uniq_mlops_release_execution",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DatasetReleaseObjectCleanup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Created Time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                ("release_type", models.CharField(max_length=100)),
                ("release_id", models.PositiveBigIntegerField()),
                ("owner_token", models.CharField(max_length=64)),
                ("object_path", models.CharField(max_length=1024)),
                (
                    "cleanup_token",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "cleanup_lease_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "mlops_dataset_release_object_cleanup",
                "indexes": [
                    models.Index(
                        fields=["release_type", "release_id"],
                        name="mlops_release_cleanup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("release_type", "release_id", "owner_token"),
                        name="uniq_mlops_release_cleanup",
                    )
                ],
            },
        ),
    ]
