# Generated by Django 4.2.27 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mlops", "0048_datasetreleaseexecution"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetReleaseObjectCleanupCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Created Time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                ("scope", models.CharField(default="global", max_length=32, unique=True)),
                ("last_intent_id", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "db_table": "mlops_dataset_release_cleanup_cursor",
            },
        ),
    ]
