# Generated by Django 4.2.27 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mlops", "0049_datasetreleaseobjectcleanupcursor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalResourceCleanupIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("mlflow_experiment_model", "MLflow experiment and model")],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("claim_token", models.CharField(blank=True, default="", max_length=64)),
                ("claim_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "mlops_external_resource_cleanup_intent",
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="mlops_ext_cleanup_due_idx",
                    ),
                ],
            },
        ),
    ]
