# Generated by Django 4.2.27 on 2026-06-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opspilot", "0059_merge_0056_llmskill_skill_packages_skillpackage_0058_bot_usage_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillpackage", name="created_at", field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(model_name="skillpackage", name="updated_at", field=models.DateTimeField(auto_now=True, verbose_name="Updated Time"),),
    ]
