# Generated by Django 4.2.27 on 2026-07-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0062_buildrecord_checkitem_knowledgepage_material_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowconversationhistory",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("restful", "RESTful"),
                    ("celery", "Celery"),
                    ("enterprise_wechat", "Enterprise WeChat"),
                    ("enterprise_wechat_aibot", "Enterprise WeChat AI Bot"),
                    ("wechat_official", "WeChat Official Account"),
                    ("dingtalk", "Ding Talk"),
                    ("embedded_chat", "Embedded Chat"),
                    ("web_chat", "Web Chat"),
                    ("mobile", "Mobile"),
                    ("agui", "AG-UI"),
                    ("nats", "NATS"),
                ],
                db_index=True,
                default="restful",
                help_text="对话入口类型：openai/restful/enterprise_wechat/wechat_official/dingtalk，celery定时触发不记录",
                max_length=50,
                verbose_name="入口类型",
            ),
        ),
    ]
