# Generated by Django 4.2.27 on 2026-07-13 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("opspilot", "0063_alter_workflowconversationhistory_entry_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkitem",
            name="decision_context",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="checkitem",
            name="decision_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="WikiDecisionRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                (
                    "decision_type",
                    models.CharField(choices=[("knowledge_conflict", "知识冲突"), ("page_identity", "页面身份")], db_index=True, max_length=40),
                ),
                ("decision_key", models.CharField(db_index=True, help_text="SHA-256 hex,普通字段唯一约束", max_length=64)),
                ("subject_key", models.CharField(blank=True, default="", help_text="可诊断的稳定知识标识", max_length=200)),
                ("match_snapshot", models.JSONField(default=dict, help_text="参与者集合 + Schema 指纹 + 输入指纹(仅审计)")),
                ("result_snapshot", models.JSONField(default=dict, help_text="胜出资料 + 最终正文指纹 + 目标身份(仅审计)")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("keep_current", "保留当前知识"),
                            ("use_new", "使用新知识"),
                            ("edit_accept", "编辑后采用"),
                            ("keep_separate", "保持页面独立"),
                            ("merge", "确认页面合并"),
                        ],
                        max_length=40,
                    ),
                ),
                ("status", models.CharField(choices=[("active", "生效中"), ("revoked", "已撤销")], db_index=True, default="active", max_length=20)),
                ("replay_count", models.IntegerField(default=0, help_text="自动回放命中次数,审计用")),
                ("last_replayed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "knowledge_base",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="decision_rules", to="opspilot.wikiknowledgebase"),
                ),
                (
                    "result_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="知识结果对应的页面(审计引用,知识合并时 result_page 是目标)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="result_decision_rules",
                        to="opspilot.knowledgepage",
                    ),
                ),
                (
                    "result_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="最终生效的页面版本(审计引用,page_id 重建后会变,故不参与主匹配)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="result_decision_rules",
                        to="opspilot.pageversion",
                    ),
                ),
                (
                    "source_check",
                    models.ForeignKey(
                        blank=True,
                        help_text="首次创建规则的检查项(审计引用,不参与主匹配)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decision_rules",
                        to="opspilot.checkitem",
                    ),
                ),
            ],
            options={
                "db_table": "opspilot_wiki_decision_rule",
                "indexes": [models.Index(fields=["status", "decision_type"], name="opspilot_wi_status_507a49_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="wikidecisionrule",
            constraint=models.UniqueConstraint(fields=("knowledge_base", "decision_type", "decision_key"), name="uniq_wiki_decision_rule_active"),
        ),
    ]
