# Generated by Django 4.2.27 on 2026-07-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0065_close_non_decision_checks"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chatapplication",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="chatapplication",
            name="app_type",
            field=models.CharField(
                choices=[("mobile", "移动端应用"), ("web_chat", "Web对话应用"), ("nats", "NATS 触发")],
                db_index=True,
                max_length=50,
                verbose_name="应用类型",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatapplication",
            unique_together={("bot", "node_id", "app_type")},
        ),
        migrations.CreateModel(
            name="BotWebChatSession",
            fields=[
                ("session_id", models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name="会话ID")),
                ("bot_id", models.IntegerField(db_index=True, verbose_name="机器人ID")),
                ("node_id", models.CharField(db_index=True, max_length=100, verbose_name="节点ID")),
                (
                    "source",
                    models.CharField(
                        choices=[("nats", "NATS"), ("web_chat", "Web Chat"), ("mobile", "Mobile")],
                        db_index=True,
                        default="web_chat",
                        max_length=20,
                        verbose_name="会话来源",
                    ),
                ),
                ("participants", models.JSONField(blank=True, default=list, verbose_name="干系人列表")),
                ("title", models.CharField(blank=True, default="", max_length=255, verbose_name="会话标题")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                ("created_by", models.CharField(blank=True, default="", max_length=100, verbose_name="创建者")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "Bot Web 对话会话",
                "verbose_name_plural": "Bot Web 对话会话",
                "db_table": "bot_mgmt_botwebchatsession",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["bot_id", "-created_at"], name="bot_mgmt_bo_bot_id_411143_idx"),
                    models.Index(fields=["bot_id", "node_id", "-created_at"], name="bot_mgmt_bo_bot_id_e5d6c3_idx"),
                    models.Index(fields=["source", "-created_at"], name="bot_mgmt_bo_source_84d38c_idx"),
                ],
            },
        ),
    ]
