# Generated by Django 4.2.27 on 2026-08-18 07:17

import django.db.models.deletion
from django.db import migrations, models


def backfill_skill_usage_team(apps, schema_editor):
    """存量智能体的使用组织初始化为管理组织。"""
    LLMSkill = apps.get_model("opspilot", "LLMSkill")
    to_update = []
    for skill in LLMSkill.objects.all().iterator():
        if not skill.usage_team:
            skill.usage_team = list(skill.team or [])
            to_update.append(skill)
    if to_update:
        LLMSkill.objects.bulk_update(to_update, ["usage_team"], batch_size=500)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0071_llmskill_skill_package_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillChannel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("name", models.CharField(blank=True, default="", max_length=100, verbose_name="name")),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("platform", "Platform"),
                            ("web_chat", "Web Chat"),
                            ("embedded_chat", "Embedded Chat"),
                            ("enterprise_wechat", "Enterprise WeChat"),
                            ("enterprise_wechat_aibot", "Enterprise WeChat AI Bot"),
                            ("dingtalk", "Ding Talk"),
                            ("wechat_official", "WeChat Official Account"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="channel type",
                    ),
                ),
                ("channel_config", models.JSONField(blank=True, default=dict, verbose_name="channel config")),
                ("enabled", models.BooleanField(db_index=True, default=False, verbose_name="enabled")),
                ("usage_team", models.JSONField(default=list, verbose_name="使用组织")),
            ],
            options={
                "verbose_name": "智能体渠道绑定",
                "verbose_name_plural": "智能体渠道绑定",
                "db_table": "model_provider_mgmt_skillchannel",
            },
        ),
        migrations.AddField(
            model_name="llmskill",
            name="usage_team",
            field=models.JSONField(default=list, verbose_name="使用组织"),
        ),
        migrations.RunPython(backfill_skill_usage_team, noop_reverse),
        migrations.CreateModel(
            name="SkillConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("session_id", models.CharField(db_index=True, max_length=100, unique=True, verbose_name="会话ID")),
                ("external_user_id", models.CharField(blank=True, db_index=True, default="", max_length=255, verbose_name="外部用户标识")),
                ("title", models.CharField(blank=True, default="", max_length=255, verbose_name="会话标题")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="conversations", to="opspilot.skillchannel", verbose_name="渠道绑定"
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="conversations", to="opspilot.llmskill", verbose_name="智能体"
                    ),
                ),
            ],
            options={
                "verbose_name": "智能体会话",
                "verbose_name_plural": "智能体会话",
                "db_table": "model_provider_mgmt_skillconversation",
            },
        ),
        migrations.AddField(
            model_name="skillchannel",
            name="skill",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="channels", to="opspilot.llmskill", verbose_name="智能体"),
        ),
        migrations.CreateModel(
            name="SkillConversationMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("user", "用户"), ("assistant", "助手")], max_length=32, verbose_name="角色")),
                ("content", models.TextField(verbose_name="内容")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="opspilot.skillconversation", verbose_name="会话"
                    ),
                ),
            ],
            options={
                "verbose_name": "智能体会话消息",
                "verbose_name_plural": "智能体会话消息",
                "db_table": "model_provider_mgmt_skillconversationmessage",
                "ordering": ["created_at", "id"],
                "indexes": [models.Index(fields=["conversation", "created_at"], name="model_provi_convers_381cce_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="skillconversation",
            index=models.Index(fields=["skill", "-created_at"], name="model_provi_skill_i_488813_idx"),
        ),
        migrations.AddIndex(
            model_name="skillconversation",
            index=models.Index(fields=["channel", "external_user_id", "-created_at"], name="model_provi_channel_8e3d06_idx"),
        ),
        migrations.AddIndex(
            model_name="skillchannel",
            index=models.Index(fields=["skill", "channel_type", "enabled"], name="model_provi_skill_i_1da013_idx"),
        ),
    ]
