[program:patch_maintenance]
command=celery -A apps.core.celery worker --loglevel=info --pool threads --concurrency=1 -Q patch_maintenance -n patch-maintenance@%%h
directory=/apps
autostart=true
priority=10
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
