# Generated by Django 4.2.27 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("patch_mgmt", "0003_normalize_cpu_architectures")]

    operations = [
        migrations.AddField(
            model_name="patchsource",
            name="builtin_key",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="内置源稳定标识",
            ),
        ),
        migrations.AddField(
            model_name="patchsource",
            name="is_builtin",
            field=models.BooleanField(db_index=True, default=False, verbose_name="是否内置"),
        ),
    ]
