# Generated by Django 4.2.27 on 2026-08-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0039_merge_cloudregion_and_winrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='cmdb_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='CMDB实例ID'),
        ),
        migrations.AddField(
            model_name='node',
            name='monitor_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='监控实例ID'),
        ),
        migrations.AddField(
            model_name='node',
            name='push_status',
            field=models.JSONField(default=dict, verbose_name='跨模块推送状态'),
        ),
    ]
