# Generated by Django 4.2.27 on 2026-07-28

from django.db import migrations, models


COMMAND_PRESETS = [
    ("禁止递归删除根目录", r"(?m)^\s*(?:sudo\s+)?rm\s+(?=[^\n]*(?:-[A-Za-z]*r[A-Za-z]*f|-[A-Za-z]*f[A-Za-z]*r))[^\n]*\s/(?:\s|$)", "forbidden"),
    ("禁止格式化块设备", r"(?m)^\s*(?:sudo\s+)?mkfs(?:\.[A-Za-z0-9_-]+)?\s+[^\n]*/dev/(?:sd|vd|xvd|nvme|mmcblk)", "forbidden"),
    ("禁止直接覆写块设备", r"(?m)^\s*(?:sudo\s+)?dd\b[^\n]*\bof=/dev/(?:sd|vd|xvd|nvme|mmcblk)", "forbidden"),
    ("禁止擦除块设备签名", r"(?m)^\s*(?:sudo\s+)?wipefs\b[^\n]*/dev/(?:sd|vd|xvd|nvme|mmcblk)", "forbidden"),
    ("禁止 Shell fork bomb", r":\s*\(\s*\)\s*\{\s*:\s*\|\s*:\s*&\s*\}\s*;\s*:", "forbidden"),
    ("Linux 关机或重启需确认", r"(?m)^\s*(?:sudo\s+)?(?:shutdown|reboot|poweroff|halt)\b", "confirm"),
    ("Linux 服务停止或重启需确认", r"(?m)^\s*(?:sudo\s+)?systemctl\s+(?:stop|restart)\b", "confirm"),
    ("禁止格式化 Windows 系统盘", r"(?im)^\s*format(?:\.com)?\s+(?:/[^\s]+\s+)*c:\s*", "forbidden"),
    ("禁止 PowerShell 递归删除系统盘", r"(?im)^\s*Remove-Item\b(?=[^\n]*-(?:Recurse|r)\b)(?=[^\n]*-(?:Force|fo)\b)[^\n]*(?:'c:\\?'|\"c:\\?\"|c:\\?)(?:\s|$)", "forbidden"),
    ("禁止 CMD 递归删除系统盘", r"(?im)^\s*(?:del|rmdir|rd)\b(?=[^\n]*/s\b)(?=[^\n]*/q\b)[^\n]*c:\\?(?:\s|$)", "forbidden"),
    ("禁止删除 Windows 启动配置", r"(?im)^\s*bcdedit(?:\.exe)?\s+/delete\b", "forbidden"),
    ("Windows 关机或重启需确认", r"(?im)^\s*(?:Stop-Computer|Restart-Computer|shutdown(?:\.exe)?\s+/(?:s|r))\b", "confirm"),
]

PATH_PRESETS = [
    *[(f"禁止分发到 {path}", path, "forbidden") for path in ("/boot", "/dev", "/proc", "/sys", "/root/.ssh", "/etc/shadow", "/etc/gshadow")],
    *[(f"分发到 {path} 需确认", path, "confirm") for path in ("/etc", "/bin", "/sbin", "/lib", "/lib64", "/usr/bin", "/usr/sbin")],
    *[(f"禁止分发到 {path}", path, "forbidden") for path in (r"C:\Boot", r"C:\Windows\System32\config", r"C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys")],
    *[(f"分发到 {path} 需确认", path, "confirm") for path in (r"C:\Windows", r"C:\Program Files", r"C:\Program Files (x86)")],
]


def seed_builtins(apps, schema_editor):
    DangerousRule = apps.get_model("job_mgmt", "DangerousRule")
    DangerousPath = apps.get_model("job_mgmt", "DangerousPath")
    JobExecution = apps.get_model("job_mgmt", "JobExecution")
    ScheduledTask = apps.get_model("job_mgmt", "ScheduledTask")
    Target = apps.get_model("job_mgmt", "Target")

    # 已有安装默认停用内置规则，避免迁移后改变现有执行策略；全新安装默认启用。
    is_fresh_install = not any(
        model.objects.exists()
        for model in (DangerousRule, DangerousPath, JobExecution, ScheduledTask, Target)
    )
    common = {
        "description": "系统内置高危基线，可由平台超级管理员维护。",
        "is_builtin": True,
        "is_enabled": is_fresh_install,
        "team": [],
        "created_by": "system",
        "updated_by": "system",
    }

    DangerousRule.objects.bulk_create([
        DangerousRule(name=name, pattern=pattern, level=level, **common)
        for name, pattern, level in COMMAND_PRESETS
    ])
    DangerousPath.objects.bulk_create([
        DangerousPath(name=name, pattern=pattern, match_type="exact", level=level, **common)
        for name, pattern, level in PATH_PRESETS
    ])


def remove_builtins(apps, schema_editor):
    apps.get_model("job_mgmt", "DangerousRule").objects.filter(is_builtin=True).delete()
    apps.get_model("job_mgmt", "DangerousPath").objects.filter(is_builtin=True).delete()


class Migration(migrations.Migration):
    dependencies = [("job_mgmt", "0012_jobexecution_callback_subject_and_more")]

    operations = [
        migrations.AddField(
            model_name="dangerousrule",
            name="is_builtin",
            field=models.BooleanField(db_index=True, default=False, verbose_name="是否内置"),
        ),
        migrations.AddField(
            model_name="dangerouspath",
            name="is_builtin",
            field=models.BooleanField(db_index=True, default=False, verbose_name="是否内置"),
        ),
        migrations.RunPython(seed_builtins, remove_builtins),
    ]
