# Generated by Django 4.2.27 on 2026-07-28

from django.db import migrations, models


def backfill_active_playbook_temp_file_keys(apps, schema_editor):
    """固定升级时仍在执行的 Playbook 临时对象 Key。

    终态记录不再需要清理；升级停流排空边界保证迁移后不再有旧 worker 创建
    缺少精确 Key 的新执行，避免为兼容而扫描共享 Object Store。
    """
    JobExecution = apps.get_model("job_mgmt", "JobExecution")
    terminal_statuses = ["success", "failed", "timeout", "cancelled"]
    executions = (
        JobExecution.objects.filter(job_type="playbook", playbook_id__isnull=False)
        .exclude(status__in=terminal_statuses)
        .filter(models.Q(playbook_temp_file_key__isnull=True) | models.Q(playbook_temp_file_key=""))
        .values_list("id", "playbook__file")
    )
    for execution_id, playbook_file in executions.iterator(chunk_size=500):
        file_name = str(playbook_file or "").rsplit("/", 1)[-1]
        if file_name:
            JobExecution.objects.filter(pk=execution_id).update(
                playbook_temp_file_key=f"job-playbooks/{execution_id}/{file_name}"
            )


class Migration(migrations.Migration):
    dependencies = [("job_mgmt", "0013_dangerous_builtin_metadata")]

    operations = [
        migrations.AddField(
            model_name="jobexecution",
            name="terminal_source",
            field=models.CharField(
                blank=True,
                choices=[("ansible_callback", "Ansible 真实回调"), ("cancel_timeout", "取消超时兜底")],
                default="",
                max_length=32,
                null=True,
                verbose_name="终态写入来源",
            ),
        ),
        migrations.AddField(
            model_name="jobexecution",
            name="playbook_temp_file_key",
            field=models.CharField(
                blank=True,
                default="",
                max_length=512,
                null=True,
                verbose_name="Playbook NATS 临时文件 Key",
            ),
        ),
        migrations.AddField(
            model_name="jobexecution",
            name="cancel_finalize_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="取消兜底收敛时间",
            ),
        ),
        migrations.RunPython(
            backfill_active_playbook_temp_file_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="JobCompletionOutbox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("execution_id", models.BigIntegerField(db_index=True, verbose_name="作业执行 ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("done_sentinel", "流结束哨兵"),
                            ("playbook_cleanup", "Playbook 临时文件清理"),
                            ("web_callback", "HTTP 回调"),
                            ("nats_callback", "NATS 回调"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="副作用类型",
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="不可变投递载荷")),
                ("idempotency_key", models.CharField(max_length=255, unique=True, verbose_name="幂等键")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待投递"),
                            ("delivering", "投递中"),
                            ("delivered", "已投递"),
                            ("failed", "投递失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="投递状态",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="尝试次数")),
                ("max_attempts", models.PositiveIntegerField(default=12, verbose_name="单周期最大尝试次数")),
                (
                    "next_retry_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="下次重试时间"),
                ),
                ("lease_token", models.UUIDField(blank=True, default=None, null=True, verbose_name="投递租约令牌")),
                (
                    "lease_expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="投递租约到期时间"),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True, verbose_name="投递完成时间")),
                ("last_error", models.TextField(blank=True, default="", verbose_name="最近错误")),
            ],
            options={
                "verbose_name": "作业完成投递",
                "verbose_name_plural": "作业完成投递",
                "db_table": "job_completion_outbox",
                "indexes": [
                    models.Index(fields=["status", "next_retry_at"], name="job_outbox_retry_idx"),
                    models.Index(fields=["status", "lease_expires_at"], name="job_outbox_lease_idx"),
                ],
            },
        ),
    ]
