import type { SimpleDashboardConfig } from '../common/simple-dashboard-core';

export const KAFKA_DASHBOARD_CONFIG: SimpleDashboardConfig = {
  routeKey: 'kafka',
  pageTitle: 'Kafka 监控仪表盘',
  objectFallbackName: 'Kafka',
  instanceType: 'kafka',
  collectionStatusQuery: "count({instance_type='kafka', collect_type='exporter', __$labels__}) by (instance_id)",
  metaItems: ['Kafka-Exporter', 'exporter'],
  metrics: [
    {
      name: 'kafka_up_gauge',
      display_name: '探针状态',
      description: 'Kafka Exporter 与 Kafka Broker 的当前连接状态。',
      unit: 'none',
      query: 'min(kafka_up_gauge{__$labels__})',
      color: '#52c41a',
    },
    {
      name: 'kafka_brokers_gauge',
      display_name: 'Broker 数',
      description: 'Kafka 集群当前可发现的 Broker 数量。',
      unit: 'counts',
      query: 'max by (instance_id) (kafka_brokers_gauge{__$labels__})',
      color: '#2f6bff',
    },
    {
      name: 'kafka_under_replicated_partitions',
      display_name: '不同步分区数',
      description: '副本未全部同步的分区数量；非零时需优先排查副本健康。',
      unit: 'counts',
      query: 'sum(kafka_topic_partition_under_replicated_partition_gauge{__$labels__})',
      color: '#ff8a1f',
    },
    {
      name: 'kafka_max_consumergroup_lag',
      display_name: '最大消费者 Lag',
      description: '所有消费者组、Topic 和分区中当前最大的消费滞后。',
      unit: 'counts',
      query: 'max(kafka_consumergroup_lag_gauge{__$labels__} >= 0)',
      color: '#ff4d4f',
    },
    {
      name: 'kafka_topic_partition_count',
      display_name: 'Topic 分区数',
      description: '当前已采集 Topic 的分区总数。',
      unit: 'counts',
      query: 'sum(kafka_topic_partitions_gauge{__$labels__})',
      color: '#13c2c2',
    },
    {
      name: 'kafka_topic_count',
      display_name: 'Topic 数',
      description: '当前已采集的 Topic 数量。',
      unit: 'counts',
      query: 'count(count by (topic) (kafka_topic_partitions_gauge{__$labels__}))',
      color: '#722ed1',
    },
    {
      name: 'kafka_consumergroup_lag_anomalies',
      display_name: '异常 Lag 分区数',
      description: '已提交偏移量大于同轮日志末端偏移量的分区数量。',
      unit: 'counts',
      query: 'sum(kafka_exporter_lag_anomalies_gauge{__$labels__})',
      color: '#ff4d4f',
    },
    {
      name: 'kafka_consumergroup_uncommitted_offsets',
      display_name: '未提交 Offset 分区数',
      description: '当前没有提交 Offset 的消费者组分区数量；不包含已被标记为异常 Lag 的分区。',
      unit: 'counts',
      // count() 在零匹配时返回空结果；补 vector(0) 使健康集群显示 0 而不是「无数据」。
      query: 'count((kafka_consumergroup_lag_gauge{__$labels__} == -1) unless on(instance_id, consumergroup, topic, partition) (kafka_consumergroup_lag_anomaly_gauge{__$labels__} == 1)) or on() vector(0)',
      color: '#faad14',
    },
  ],
  summaryCards: [
    {
      title: '探针状态',
      metric: 'kafka_up_gauge',
      unit: 'none',
      color: '#52c41a',
      icon: 'health',
      enumMap: { 0: { label: '异常', color: '#ff4d4f' }, 1: { label: '正常', color: '#52c41a' } },
      guide: [{ label: '探针连接', detail: '0 表示 Exporter 本轮无法连接 Kafka；无数据则需同时检查探针进程和 Telegraf 采集链路。' }],
    },
    {
      title: 'Broker 数',
      metric: 'kafka_brokers_gauge',
      unit: 'counts',
      color: '#2f6bff',
      icon: 'node',
      guide: [{ label: 'Broker 数', detail: 'Broker 数突变可能表示节点离线、扩缩容或采集异常。' }],
    },
    {
      title: '不同步分区数',
      metric: 'kafka_under_replicated_partitions',
      unit: 'counts',
      color: '#ff8a1f',
      icon: 'health',
      compare: true,
      compareFavorableDirection: 'down',
      guide: [{ label: '副本同步', detail: '正常状态为 0；非零表示至少一个分区未达到 ISR 副本要求。' }],
    },
    {
      title: '最大消费者 Lag',
      metric: 'kafka_max_consumergroup_lag',
      unit: 'counts',
      color: '#ff4d4f',
      icon: 'backlog',
      compare: true,
      compareFavorableDirection: 'down',
      guide: [{ label: '消费者 Lag', detail: '取当前最严重的消费者组分区滞后；持续升高说明消费速度落后于生产。' }],
    },
    {
      title: 'Topic 分区数',
      metric: 'kafka_topic_partition_count',
      unit: 'counts',
      color: '#13c2c2',
      icon: 'database',
      guide: [{ label: '分区规模', detail: '分区总数反映当前被监控集群的 Topic 和并行度规模。' }],
    },
    {
      title: 'Topic 数',
      metric: 'kafka_topic_count',
      unit: 'counts',
      color: '#722ed1',
      icon: 'database',
      guide: [{ label: 'Topic 规模', detail: '仅展示当前采集范围内的 Topic 总数。' }],
    },
    {
      title: '异常 Lag 分区数',
      metric: 'kafka_consumergroup_lag_anomalies',
      unit: 'counts',
      color: '#ff4d4f',
      icon: 'backlog',
      compare: true,
      compareFavorableDirection: 'down',
      guide: [{ label: '异常 Lag', detail: '表示已提交 Offset 大于同轮 LEO；保留原始负 Lag 供排查。' }],
    },
    {
      title: '未提交 Offset 分区数',
      metric: 'kafka_consumergroup_uncommitted_offsets',
      unit: 'counts',
      color: '#faad14',
      icon: 'backlog',
      guide: [{ label: '未提交 Offset', detail: 'Lag 为 -1 且未标记为异常，表示该消费者组分区没有提交 Offset。无此类分区时显示 0。' }],
    },
  ],
  charts: [
    {
      title: '消费者 Lag 趋势',
      subtitle: '最大消费者组分区 Lag',
      metric: 'kafka_max_consumergroup_lag',
      guide: [{ label: 'Lag 趋势', detail: '折线展示最大 Lag 的时间变化；悬浮任一点可查看精确数值和时间。' }],
      series: [{ metric: 'kafka_max_consumergroup_lag', label: '最大 Lag', color: '#ff4d4f', unit: 'counts' }],
    },
    {
      title: '分区副本健康趋势',
      subtitle: '不同步副本分区数',
      metric: 'kafka_under_replicated_partitions',
      guide: [{ label: '副本健康', detail: '折线应稳定在 0；非零点表示需要检查 Broker、网络或磁盘同步。' }],
      series: [{ metric: 'kafka_under_replicated_partitions', label: '不同步分区', color: '#ff8a1f', unit: 'counts' }],
    },
  ],
  details: [],
};
