# Generated by Django 4.2.27 on 2026-07-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb", "0030_alter_collectmodels_input_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dedupe_key", models.CharField(max_length=64, unique=True, verbose_name="去重键")),
                ("rule_id_snapshot", models.BigIntegerField(verbose_name="订阅规则ID快照")),
                ("trigger_type", models.CharField(max_length=32, verbose_name="触发类型")),
                ("events", models.JSONField(default=list, verbose_name="触发事件")),
                ("recipients", models.JSONField(default=dict, verbose_name="接收对象")),
                ("channel_id", models.BigIntegerField(verbose_name="通知渠道ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待发送"), ("sending", "发送中"), ("retry", "待重试"), ("sent", "已发送"), ("failed", "发送失败")],
                        default="pending",
                        max_length=16,
                        verbose_name="投递状态",
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0, verbose_name="尝试次数")),
                ("next_retry_at", models.DateTimeField(blank=True, null=True, verbose_name="下次重试时间")),
                ("last_error", models.TextField(blank=True, default="", verbose_name="最近错误")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="发送时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="cmdb.subscriptionrule",
                        verbose_name="订阅规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "订阅通知投递",
                "verbose_name_plural": "订阅通知投递",
                "db_table": "cmdb_subscription_delivery",
                "indexes": [
                    models.Index(fields=["status", "next_retry_at"], name="idx_sub_del_status_retry"),
                    models.Index(fields=["rule_id_snapshot", "created_at"], name="idx_sub_del_rule_created"),
                ],
            },
        ),
    ]
