# Generated by Django 4.2.25 on 2026-07-13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("cmdb", "0033_config_file_content_lifecycle")]

    operations = [
        migrations.CreateModel(
            name="IPAMReconcileRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("run_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "active_scope",
                    models.CharField(default="global", editable=False, max_length=32, null=True, unique=True),
                ),
                ("trigger", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("error", "失败"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("owner_token", models.CharField(blank=True, default="", max_length=64)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "cmdb_ipam_reconcile_run"},
        ),
        migrations.AddIndex(
            model_name="ipamreconcilerun",
            index=models.Index(fields=["status", "lease_expires_at"], name="cmdb_ipam_run_lease_idx"),
        ),
    ]
