# Generated by Django 4.2.25 on 2026-07-13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("cmdb", "0034_ipam_reconcile_run")]

    operations = [
        migrations.CreateModel(
            name="CmdbOperation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("operation_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("operator", models.CharField(max_length=128)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=64)),
                ("target", models.JSONField(blank=True, default=dict)),
                ("request_snapshot", models.JSONField(blank=True, default=dict)),
                ("result_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待图写"),
                            ("graph_writing", "图写执行中"),
                            ("graph_committed", "图写已提交"),
                            ("completed", "已完成"),
                            ("error", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("owner_token", models.CharField(blank=True, default="", max_length=64)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "cmdb_operation"},
        ),
        migrations.CreateModel(
            name="CmdbOperationOutbox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待投递"),
                            ("sending", "投递中"),
                            ("retry", "等待重试"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("owner_token", models.CharField(blank=True, default="", max_length=64)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_events",
                        to="cmdb.cmdboperation",
                    ),
                ),
            ],
            options={"db_table": "cmdb_operation_outbox"},
        ),
        migrations.AddIndex(
            model_name="cmdboperation",
            index=models.Index(fields=["status", "lease_expires_at"], name="cmdb_operation_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="cmdboperation",
            constraint=models.UniqueConstraint(
                fields=("operator", "idempotency_key"),
                name="uniq_cmdb_operation_idempotency",
            ),
        ),
        migrations.AddIndex(
            model_name="cmdboperationoutbox",
            index=models.Index(fields=["status", "lease_expires_at"], name="cmdb_op_outbox_lease_idx"),
        ),
        migrations.AddConstraint(
            model_name="cmdboperationoutbox",
            constraint=models.UniqueConstraint(
                fields=("operation", "event_type"),
                name="uniq_cmdb_operation_event",
            ),
        ),
    ]
