# Generated by Django 4.2.27 on 2026-08-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0045_instance_uuid_transition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configfileversion",
            name="instance_id",
            field=models.CharField(help_text="主机实例图 ID（过渡期保留）", max_length=128),
        ),
    ]
