# Generated by Django 4.2.27 on 2026-06-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0033_operationlog_target_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkWhiteList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("network", models.CharField(max_length=64, unique=True)),
                ("remark", models.CharField(default="", max_length=255)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Network White List",
                "db_table": "system_mgmt_network_white_list",
                "ordering": ["-id"],
            },
        ),
    ]
