# Generated by Django 4.2.27 on 2026-06-05 02:24

import apps.core.mixinx
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0034_networkwhitelist"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=100)),
                ("provider_key", models.CharField(db_index=True, max_length=64)),
                ("config", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pending Verification"),
                            ("ready", "Ready"),
                            ("verification_failed", "Verification Failed"),
                        ],
                        default="pending_verification",
                        max_length=32,
                    ),
                ),
                ("capability_status", models.JSONField(default=dict)),
                ("capability_enabled", models.JSONField(default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
                ("team", models.JSONField(default=list)),
            ],
            options={
                "ordering": ("-id",),
            },
            bases=(models.Model, apps.core.mixinx.EncryptMixin),
        ),
    ]
