# Generated by Django 4.2.27 on 2026-06-05 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0035_integrationinstance"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAuthBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, default="", max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("external_field", models.CharField(max_length=100)),
                (
                    "platform_field",
                    models.CharField(
                        choices=[
                            ("username", "Platform Username"),
                            ("phone", "Platform Mobile"),
                            ("email", "Platform Email"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "unmatched_user_action",
                    models.CharField(
                        choices=[("deny", "Deny Login"), ("create", "Create User")],
                        default="deny",
                        max_length=16,
                    ),
                ),
                ("default_group_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "integration_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_auth_bindings",
                        to="system_mgmt.integrationinstance",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "unique_together": {("name", "integration_instance")},
            },
        ),
    ]
