# Generated by Django 4.2.27 on 2026-06-05 02:45

import apps.core.mixinx
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0036_loginauthbinding"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSyncSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
                ("root_group_name", models.CharField(max_length=100)),
                ("field_mapping", models.JSONField(blank=True, default=dict)),
                ("schedule_config", models.JSONField(blank=True, default=dict)),
                ("business_config", models.JSONField(blank=True, default=dict)),
                (
                    "integration_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sync_sources",
                        to="system_mgmt.integrationinstance",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
                "unique_together": {("name", "integration_instance")},
            },
            bases=(models.Model, apps.core.mixinx.PeriodicTaskUtils),
        ),
        migrations.CreateModel(
            name="UserSyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("trigger_mode", models.CharField(choices=[("manual", "Manual"), ("schedule", "Schedule")], default="manual", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=16,
                    ),
                ),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                ("synced_user_count", models.PositiveIntegerField(default=0)),
                ("synced_group_count", models.PositiveIntegerField(default=0)),
                ("disabled_user_count", models.PositiveIntegerField(default=0)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="system_mgmt.usersyncsource",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "running")),
                        fields=("source",),
                        name="unique_running_user_sync_run_per_source",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="group",
            name="sync_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="synced_groups",
                to="system_mgmt.usersyncsource",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sync_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="synced_users",
                to="system_mgmt.usersyncsource",
            ),
        ),
    ]
