# Generated by Django 4.2.27 on 2026-06-17 10:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0037_usersyncsource_usersyncrun_group_sync_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IMNotificationChannel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_sync", "Pending Sync"),
                            ("ready", "Ready"),
                            ("needs_resync", "Needs Resync"),
                            ("disabled", "Disabled"),
                        ],
                        default="pending_sync",
                        max_length=32,
                    ),
                ),
                (
                    "platform_match_field",
                    models.CharField(
                        choices=[
                            ("username", "Platform Username"),
                            ("email", "Platform Email"),
                            ("phone", "Platform Mobile"),
                        ],
                        default="email",
                        max_length=32,
                    ),
                ),
                ("external_match_field", models.CharField(default="email", max_length=64)),
                ("external_receive_field", models.CharField(default="user_id", max_length=64)),
                ("schedule_config", models.JSONField(blank=True, default=dict)),
                ("team", models.JSONField(blank=True, default=list)),
                (
                    "integration_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="im_notification_channels",
                        to="system_mgmt.integrationinstance",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
                "unique_together": {("name", "integration_instance")},
            },
        ),
        migrations.CreateModel(
            name="IMNotificationSyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("trigger_mode", models.CharField(choices=[("manual", "Manual"), ("schedule", "Schedule")], default="manual", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=32,
                    ),
                ),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                ("total_external_user_count", models.PositiveIntegerField(default=0)),
                ("matched_count", models.PositiveIntegerField(default=0)),
                ("unmatched_count", models.PositiveIntegerField(default=0)),
                ("conflict_count", models.PositiveIntegerField(default=0)),
                ("locked_config_snapshot", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_runs",
                        to="system_mgmt.imnotificationchannel",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "running")),
                        fields=("channel",),
                        name="unique_running_im_notification_sync_run_per_channel",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IMNotificationUserMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("external_identity_key", models.CharField(max_length=64)),
                ("external_identity_value", models.CharField(max_length=255)),
                ("external_receive_key", models.CharField(max_length=64)),
                ("external_display_name", models.CharField(blank=True, default="", max_length=150)),
                ("match_context", models.JSONField(blank=True, default=dict)),
                ("external_snapshot", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_mappings",
                        to="system_mgmt.imnotificationchannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="im_notification_mappings",
                        to="system_mgmt.user",
                    ),
                ),
            ],
            options={
                "ordering": ("-synced_at", "-id"),
                "unique_together": {("channel", "user"), ("channel", "external_identity_key", "external_identity_value")},
            },
        ),
    ]
