# Generated by Django 4.2.27 on 2026-07-15 10:31

import uuid

from django.db import migrations, models
from django.db.models import Q


def backfill_user_id(apps, schema_editor):
    User = apps.get_model("system_mgmt", "User")

    batch = []
    queryset = User.objects.filter(Q(user_id__isnull=True) | Q(user_id="")).only("id", "user_id")
    for user in queryset.iterator(chunk_size=500):
        user.user_id = str(uuid.uuid4())
        batch.append(user)

        if len(batch) >= 500:
            User.objects.bulk_update(batch, ["user_id"], batch_size=500)
            batch = []

    if batch:
        User.objects.bulk_update(batch, ["user_id"], batch_size=500)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('system_mgmt', '0038_imnotificationchannel_imnotificationusermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=36, null=True),
        ),
        migrations.RunPython(backfill_user_id, noop_reverse),
    ]
