# Generated by Django 4.2.27 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_mgmt", "0039_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersyncsource",
            name="platform_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
