# Generated by Django 4.2.27 on 2026-08-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0046_encrypt_bk_login_app_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_delete",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
