OPSPILOT_GUEST_MENUS = [
    "bot_list-View",
    "bot_list-Add",
    "bot_list-Edit",
    "bot_list-Delete",
    "bot_settings-View",
    "bot_settings-Edit",
    "bot_settings-Test",
    "bot_settings-Mark",
    "bot_channel-View",
    "bot_conversation_log-View",
    "bot_statistics-View",
    "skill_list-View",
    "skill_list-Add",
    "skill_list-Edit",
    "skill_list-Delete",
    "skill_setting-View",
    "skill_setting-Edit",
    "skill_setting-Test",
    "skill_setting-Mark",
    "skill_rule-View",
    "skill_rule-Add",
    "skill_rule-Edit",
    "skill_rule-Delete",
    "skill_invocation_logs-View",
    "wiki_list-View",
    "wiki_list-Add",
    "wiki_list-Edit",
    "wiki_list-Delete",
    "provide_list-View",
    "tool_list-View",
    "my_quota-View",
]

CMDB_MENUS = [
    "asset_info-View",
    "asset_info-Add",
    "asset_info-Edit",
    "asset_info-Delete",
    "asset_info-Add Associate",
    "asset_info-Delete Associate",
    "auto_collection-View",
    "auto_collection-Add",
    "auto_collection-Edit",
    "search-View",
    "auto_collection-Delete",
    "auto_collection-Execute",
    "soid_library-View",
    "collection_tool-View",
    "collection_tool-Execute",
    "model_management-View",
    "model_management-Add Model",
    "model_management-Add Group",
    "model_management-Edit Model",
    "model_management-Edit Group",
    "model_management-Delete Group",
    "model_management-Delete Model",
]
MONITOR_MENUS = [
    "search-View",
    "view_list-View",
    "view_list-Detail",
    "alert_list-View",
    "alert_list-Operate",
    "strategy_list-View",
    "strategy_list-Add",
    "strategy_list-Edit",
    "strategy_list-Delete",
    "template_list-View",
    "integration_list-Setting",
    "integration_list-View",
    "integration_configure-View",
    "integration_configure-Add",
    "asset-View",
    "asset-Edit",
    "asset-Delete",
    "integration_metric-View",
]
