# Generated by Django 4.2.27 on 2026-07-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0016_event_notified_event_notice_retry_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemVectorConfigState",
            fields=[
                ("scope", models.CharField(default="global", editable=False, max_length=20, primary_key=True, serialize=False)),
                ("desired_generation", models.PositiveBigIntegerField(default=0)),
                ("published_generation", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("generating", "Generating"), ("published", "Published"), ("failed", "Failed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("published_content", models.TextField(blank=True, default="")),
                ("published_checksum", models.CharField(blank=True, default="", max_length=71)),
                ("last_error", models.CharField(blank=True, default="", max_length=500)),
                ("last_published_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemVectorToken",
            fields=[
                ("scope", models.CharField(default="global", editable=False, max_length=20, primary_key=True, serialize=False)),
                ("token_digest", models.CharField(max_length=256)),
                ("rotated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LogExtractor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=200)),
                ("condition", models.JSONField(default=dict)),
                (
                    "extractor_type",
                    models.CharField(
                        choices=[
                            ("copy", "Copy"),
                            ("split", "Split"),
                            ("kv", "Key Value"),
                            ("regex", "Regex"),
                            ("regex_replace", "Regex Replace"),
                            ("json", "JSON"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_field", models.CharField(default="message", max_length=500)),
                ("target_field", models.CharField(blank=True, max_length=500, null=True)),
                ("delete_source", models.BooleanField(default=False)),
                ("config", models.JSONField(default=dict)),
                ("sort_order", models.PositiveSmallIntegerField()),
                (
                    "collect_instance",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="log_extractors", to="log.collectinstance"
                    ),
                ),
            ],
            options={
                "ordering": ("collect_instance_id", "sort_order", "id"),
                "indexes": [models.Index(fields=["collect_instance", "sort_order", "id"], name="log_extractor_order_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="logextractor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("collect_instance__isnull", False)), fields=("collect_instance", "name"), name="log_extractor_instance_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="logextractor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("collect_instance__isnull", False)),
                fields=("collect_instance", "sort_order"),
                name="log_extractor_instance_order_uniq",
            ),
        ),
    ]
