# Generated by Django 4.2.27 on 2026-07-30 09:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApmAlertOutbox',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=256, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('delivery_status', models.CharField(choices=[('pending', '待投递'), ('delivered', '已投递')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'APM 告警投递箱',
                'verbose_name_plural': 'APM 告警投递箱',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ApmIngestSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('ingest_type', models.CharField(choices=[('otlp_http', 'OTLP/HTTP'), ('otlp_grpc', 'OTLP/gRPC')], max_length=32)),
                ('cloud_region_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('environment_hint', models.CharField(blank=True, default='', max_length=128)),
                ('credential_digest', models.CharField(max_length=256)),
                ('credential_prefix', models.CharField(db_index=True, max_length=24)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('first_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_received_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'APM 接入源',
                'verbose_name_plural': 'APM 接入源',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ApmIngestSourceOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('organization', models.BigIntegerField(db_index=True)),
            ],
            options={
                'verbose_name': 'APM 接入源组织',
                'verbose_name_plural': 'APM 接入源组织',
            },
        ),
        migrations.CreateModel(
            name='ApmPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('environment', models.CharField(max_length=256)),
                ('metric_type', models.CharField(choices=[('error_rate', '错误率'), ('p95', 'P95'), ('p99', 'P99'), ('throughput', '吞吐'), ('no_traffic', '无流量')], max_length=32)),
                ('comparator', models.CharField(choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<=')], max_length=8)),
                ('threshold', models.DecimalField(decimal_places=6, max_digits=20)),
                ('duration_window', models.PositiveIntegerField()),
                ('recovery_window', models.PositiveIntegerField()),
                ('severity', models.CharField(choices=[('critical', '严重'), ('error', '错误'), ('warning', '警告')], max_length=16)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'APM 策略',
                'verbose_name_plural': 'APM 策略',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ApmPolicyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('evaluation_cursor', models.CharField(blank=True, default='', max_length=512)),
                ('consecutive_hits', models.PositiveIntegerField(default=0)),
                ('consecutive_recoveries', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('normal', '正常'), ('firing', '告警')], default='normal', max_length=16)),
                ('last_succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('external_alert_id', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'verbose_name': 'APM 策略状态',
                'verbose_name_plural': 'APM 策略状态',
            },
        ),
        migrations.CreateModel(
            name='ApmService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(blank=True, default='', max_length=256)),
                ('normalized_namespace', models.CharField(blank=True, default='', max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('normalized_name', models.CharField(max_length=256)),
                ('first_seen_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'verbose_name': 'APM 服务',
                'verbose_name_plural': 'APM 服务',
                'ordering': ('normalized_namespace', 'normalized_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ApmServiceInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=512)),
                ('normalized_instance_id', models.CharField(max_length=512)),
                ('environment', models.CharField(blank=True, default='', max_length=256)),
                ('version', models.CharField(blank=True, default='', max_length=256)),
                ('permission_mode', models.CharField(choices=[('inherited', '继承接入源'), ('custom', '自定义')], default='inherited', max_length=16)),
                ('first_seen_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.CharField(blank=True, default='', max_length=256)),
                ('ingest_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='apm.apmingestsource')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='apm.apmservice')),
            ],
            options={
                'verbose_name': 'APM 服务实例',
                'verbose_name_plural': 'APM 服务实例',
                'ordering': ('service_id', 'normalized_instance_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ApmServiceOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('organization', models.BigIntegerField(db_index=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='apm.apmservice')),
            ],
            options={
                'verbose_name': 'APM 服务组织',
                'verbose_name_plural': 'APM 服务组织',
            },
        ),
        migrations.CreateModel(
            name='ApmServiceInstanceOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('organization', models.BigIntegerField(db_index=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='apm.apmserviceinstance')),
            ],
            options={
                'verbose_name': 'APM 服务实例组织',
                'verbose_name_plural': 'APM 服务实例组织',
            },
        ),
        migrations.AddConstraint(
            model_name='apmservice',
            constraint=models.UniqueConstraint(fields=('normalized_namespace', 'normalized_name'), name='apm_service_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='apmservice',
            constraint=models.CheckConstraint(check=models.Q(('normalized_name', ''), _negated=True), name='apm_service_name_not_empty'),
        ),
        migrations.AddField(
            model_name='apmpolicystate',
            name='policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='apm.apmpolicy'),
        ),
        migrations.AddField(
            model_name='apmpolicy',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='apm.apmservice'),
        ),
        migrations.AddField(
            model_name='apmingestsourceorganization',
            name='ingest_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='apm.apmingestsource'),
        ),
        migrations.AddConstraint(
            model_name='apmserviceorganization',
            constraint=models.UniqueConstraint(fields=('service', 'organization'), name='apm_service_org_unique'),
        ),
        migrations.AddConstraint(
            model_name='apmserviceinstanceorganization',
            constraint=models.UniqueConstraint(fields=('instance', 'organization'), name='apm_instance_org_unique'),
        ),
        migrations.AddConstraint(
            model_name='apmserviceinstance',
            constraint=models.UniqueConstraint(fields=('service', 'normalized_instance_id'), name='apm_service_instance_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='apmserviceinstance',
            constraint=models.CheckConstraint(check=models.Q(('normalized_instance_id', ''), _negated=True), name='apm_instance_id_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='apmingestsourceorganization',
            constraint=models.UniqueConstraint(fields=('ingest_source', 'organization'), name='apm_ingest_source_org_unique'),
        ),
    ]
