# Generated by Django 4.2.27 on 2026-08-04 08:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_applications(apps, schema_editor):
    Application = apps.get_model('apm', 'ApmApplication')
    ApplicationOrganization = apps.get_model('apm', 'ApmApplicationOrganization')
    Service = apps.get_model('apm', 'ApmService')

    for service in Service.objects.exclude(normalized_namespace='').iterator():
        application_id = service.normalized_namespace
        if len(application_id) > 128:
            continue
        application, _ = Application.objects.get_or_create(
            application_id=application_id,
            defaults={
                'name': service.namespace or application_id,
                'description': '由历史 APM 服务自动迁移',
                'created_by': 'migration',
                'updated_by': 'migration',
            },
        )
        organization_ids = service.organization_links.values_list('organization', flat=True)
        ApplicationOrganization.objects.bulk_create(
            [
                ApplicationOrganization(
                    application=application,
                    organization=organization_id,
                    created_by='migration',
                    updated_by='migration',
                )
                for organization_id in organization_ids
            ],
            ignore_conflicts=True,
        )
        service.application = application
        service.save(update_fields=('application',))


def clear_applications(apps, schema_editor):
    Service = apps.get_model('apm', 'ApmService')
    Service.objects.update(application=None)


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0005_apm_slo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApmApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'APM 应用',
                'verbose_name_plural': 'APM 应用',
                'ordering': ('application_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ApmApplicationOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('organization', models.BigIntegerField(db_index=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='apm.apmapplication')),
            ],
            options={
                'verbose_name': 'APM 应用组织',
                'verbose_name_plural': 'APM 应用组织',
            },
        ),
        migrations.AddField(
            model_name='apmservice',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='apm.apmapplication'),
        ),
        migrations.AddConstraint(
            model_name='apmapplicationorganization',
            constraint=models.UniqueConstraint(fields=('application', 'organization'), name='apm_application_org_unique'),
        ),
        migrations.RunPython(backfill_applications, clear_applications),
        migrations.RemoveField(
            model_name='apmingestsourceorganization',
            name='ingest_source',
        ),
        migrations.RemoveField(
            model_name='apmserviceinstance',
            name='ingest_source',
        ),
        migrations.AlterField(
            model_name='apmserviceinstance',
            name='permission_mode',
            field=models.CharField(choices=[('inherited', '继承应用'), ('custom', '自定义')], default='inherited', max_length=16),
        ),
        migrations.DeleteModel(
            name='ApmIngestSource',
        ),
        migrations.DeleteModel(
            name='ApmIngestSourceOrganization',
        ),
    ]
