# Generated by Django 4.2.27 on 2026-08-14 09:24

import uuid
from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models

import apps.core.fields.s3_json_field


def migrate_policy_alert_event_contract(apps, schema_editor):
    Policy = apps.get_model("apm", "ApmPolicy")
    Alert = apps.get_model("apm", "ApmAlert")
    Event = apps.get_model("apm", "ApmEvent")
    Snapshot = apps.get_model("apm", "ApmEventSnapshot")
    PolicyState = apps.get_model("apm", "ApmPolicyState")

    for policy in Policy.objects.order_by("id").iterator():
        policy.metric_window = policy.duration_window
        policy.trigger_after = policy.duration_window
        policy.recover_after = policy.recovery_window
        policy.thresholds = [
            {
                "severity": policy.severity,
                "comparator": policy.comparator,
                "value": str(policy.threshold),
            }
        ]
        policy.save(update_fields=("metric_window", "trigger_after", "recover_after", "thresholds"))

    Alert.objects.filter(status="firing").update(status="active")
    PolicyState.objects.filter(status="firing").update(status="active")
    Event.objects.filter(action="created").update(action="triggered")
    Event.objects.filter(action="recovery").update(action="recovered")

    for event in Event.objects.select_related("alert", "alert__policy").order_by("id").iterator():
        alert = event.alert
        policy = alert.policy
        policy_snapshot = {
            "id": alert.policy_id_snapshot,
            "name": alert.policy_name,
            "metric_type": alert.metric_type,
        }
        if policy is not None:
            policy_snapshot.update(
                {
                    "alert_name": policy.alert_name,
                    "evaluation_interval": policy.evaluation_interval,
                    "metric_window": policy.metric_window,
                    "aggregation": policy.aggregation,
                    "thresholds": policy.thresholds,
                    "trigger_after": policy.trigger_after,
                    "recover_after": policy.recover_after,
                    "no_data_after": policy.no_data_after,
                    "no_data_severity": policy.no_data_severity,
                }
            )
        Snapshot.objects.get_or_create(
            source_event_id=event.event_id,
            defaults={
                "alert": alert,
                "event": event,
                "schema_version": 1,
                "action": event.action,
                "occurred_at": event.occurred_at,
                "organizations": event.organizations,
                "policy_snapshot": policy_snapshot,
                "object_snapshot": {
                    "service_id": event.resource_id,
                    "service_namespace": alert.service_namespace,
                    "service_name": alert.service_name,
                    "endpoint": alert.endpoint,
                    "environment": alert.environment,
                    "version": alert.version,
                },
                "evaluation_snapshot": {
                    "value": str(event.value) if event.value is not None else None,
                    "unit": "",
                    "comparator": policy.comparator if policy is not None else None,
                    "threshold": str(policy.threshold) if policy is not None else None,
                    "severity": event.severity,
                    "data_state": "available" if event.value is not None else "no_data",
                },
                "trace_context": {
                    "service_namespace": alert.service_namespace,
                    "service_name": alert.service_name,
                    "endpoint": alert.endpoint,
                    "environment": alert.environment,
                    "version": alert.version,
                },
                "payload_status": "unavailable",
                "payload_error_code": "legacy_snapshot_unavailable",
                "retention_expires_at": event.occurred_at + timedelta(days=90),
            },
        )


def restore_legacy_policy_alert_event_contract(apps, schema_editor):
    Alert = apps.get_model("apm", "ApmAlert")
    Event = apps.get_model("apm", "ApmEvent")
    PolicyState = apps.get_model("apm", "ApmPolicyState")
    Alert.objects.filter(status="active").update(status="firing")
    PolicyState.objects.filter(status="active").update(status="firing")
    Event.objects.filter(action="triggered").update(action="created")
    Event.objects.filter(action="recovered").update(action="recovery")


class Migration(migrations.Migration):
    dependencies = [
        ("apm", "0009_service_language_remove_builtin_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApmEventSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_event_id", models.CharField(max_length=320, unique=True)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "action",
                    models.CharField(choices=[("triggered", "触发"), ("escalated", "级别升级"), ("recovered", "恢复"), ("closed", "人工关闭")], max_length=16),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("organizations", models.JSONField(default=list)),
                ("policy_snapshot", models.JSONField(default=dict)),
                ("object_snapshot", models.JSONField(default=dict)),
                ("evaluation_snapshot", models.JSONField(default=dict)),
                ("trace_context", models.JSONField(default=dict)),
                (
                    "payload_status",
                    models.CharField(
                        choices=[("pending", "待写入"), ("available", "可用"), ("unavailable", "不可用"), ("expired", "已过期")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("payload_error_code", models.CharField(blank=True, default="", max_length=128)),
                ("payload_error_message", models.CharField(blank=True, default="", max_length=512)),
                ("payload_attempts", models.PositiveIntegerField(default=0)),
                ("pending_payload", models.JSONField(default=dict)),
                ("retention_expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "APM 事件快照",
                "verbose_name_plural": "APM 事件快照",
                "ordering": ("occurred_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="apmalert",
            name="endpoint",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="apmalert",
            name="operator",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="apmalert",
            name="version",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="apmpolicy",
            name="aggregation",
            field=models.CharField(choices=[("avg", "平均值"), ("max", "最大值"), ("min", "最小值"), ("last", "最新值")], default="avg", max_length=16),
        ),
        migrations.AddField(
            model_name="apmpolicy",
            name="alert_name",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="apmpolicy",
            name="endpoints",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="apmpolicy",
            name="evaluation_interval",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="apmpolicy",
            name="metric_window",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="apmpolicy",
            name="no_data_after",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apmpolicy",
            name="no_data_severity",
            field=models.CharField(blank=True, choices=[("critical", "严重"), ("error", "错误"), ("warning", "警告")], default="", max_length=16),
        ),
        migrations.AddField(
            model_name="apmpolicy",
            name="recover_after",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="apmpolicy",
            name="thresholds",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="apmpolicy",
            name="trigger_after",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="apmpolicy",
            name="version_mode",
            field=models.CharField(choices=[("all", "全部版本"), ("specific", "指定版本"), ("grouped", "按版本")], default="all", max_length=16),
        ),
        migrations.AddField(
            model_name="apmpolicy",
            name="versions",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="apmalert",
            name="status",
            field=models.CharField(
                choices=[("active", "告警中"), ("recovered", "已恢复"), ("closed", "已关闭")], db_index=True, default="active", max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="apmevent",
            name="action",
            field=models.CharField(
                choices=[("triggered", "触发"), ("escalated", "级别升级"), ("recovered", "恢复"), ("closed", "人工关闭")],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="apmpolicystate",
            name="status",
            field=models.CharField(choices=[("normal", "正常"), ("active", "告警")], default="normal", max_length=16),
        ),
        migrations.CreateModel(
            name="ApmEventSnapshotPayload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "data",
                    apps.core.fields.s3_json_field.S3JSONField(
                        bucket_name="apm-alert-snapshots",
                        compressed=True,
                        delete_previous_on_update=False,
                        max_length=500,
                        verbose_name="APM 事件指标序列",
                    ),
                ),
                ("snapshot", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="payload", to="apm.apmeventsnapshot")),
            ],
            options={
                "verbose_name": "APM 事件快照载荷",
                "verbose_name_plural": "APM 事件快照载荷",
            },
        ),
        migrations.AddField(
            model_name="apmeventsnapshot",
            name="alert",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="snapshots", to="apm.apmalert"),
        ),
        migrations.AddField(
            model_name="apmeventsnapshot",
            name="event",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="snapshot", to="apm.apmevent"),
        ),
        migrations.CreateModel(
            name="ApmPolicyTargetState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("target_key", models.CharField(max_length=512)),
                ("endpoint", models.CharField(blank=True, default="", max_length=512)),
                ("version", models.CharField(blank=True, default="", max_length=256)),
                ("evaluation_cursor", models.CharField(blank=True, default="", max_length=512)),
                ("consecutive_hits", models.PositiveIntegerField(default=0)),
                ("consecutive_recoveries", models.PositiveIntegerField(default=0)),
                ("consecutive_no_data", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("normal", "正常"), ("active", "告警中")], default="normal", max_length=16)),
                (
                    "current_severity",
                    models.CharField(blank=True, choices=[("critical", "严重"), ("error", "错误"), ("warning", "警告")], default="", max_length=16),
                ),
                ("active_alert_id", models.CharField(blank=True, default="", max_length=256)),
                ("last_succeeded_at", models.DateTimeField(blank=True, null=True)),
                ("last_failed_at", models.DateTimeField(blank=True, null=True)),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="target_states", to="apm.apmpolicy")),
            ],
            options={
                "verbose_name": "APM 策略目标状态",
                "verbose_name_plural": "APM 策略目标状态",
                "indexes": [models.Index(fields=["policy", "status"], name="apm_policy_target_status_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="apmpolicytargetstate",
            constraint=models.UniqueConstraint(fields=("policy", "target_key"), name="apm_policy_target_state_unique"),
        ),
        migrations.AddIndex(
            model_name="apmeventsnapshot",
            index=models.Index(fields=["alert", "occurred_at"], name="apm_snapshot_alert_time_idx"),
        ),
        migrations.RunPython(
            migrate_policy_alert_event_contract,
            restore_legacy_policy_alert_event_contract,
        ),
    ]
