# Generated by Django 4.2.27 on 2026-08-24 06:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0013_apmalertmetricsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApmDeploymentEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(max_length=256)),
                ('version', models.CharField(max_length=256)),
                ('deployed_at', models.DateTimeField(db_index=True)),
                ('deployed_by', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('success', '成功'), ('in_progress', '进行中'), ('rollback', '回滚'), ('failed', '失败')], db_index=True, max_length=16)),
                ('source', models.CharField(choices=[('inferred', '推断'), ('reported', '上报')], default='inferred', max_length=16)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_events', to='apm.apmservice')),
            ],
            options={
                'verbose_name': 'APM 部署事件',
                'verbose_name_plural': 'APM 部署事件',
                'ordering': ('-deployed_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='apmdeploymentevent',
            constraint=models.CheckConstraint(check=models.Q(('version', ''), _negated=True), name='apm_deployment_event_version_not_empty'),
        ),
    ]
