import { defineConfig, globalIgnores } from 'eslint/config';
import nextConfig from 'eslint-config-next';
import nextTs from 'eslint-config-next/typescript';
import storybook from 'eslint-plugin-storybook';

export default defineConfig([
  ...nextConfig,
  ...nextTs,
  ...storybook.configs['flat/recommended'],
  {
    rules: {
      '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
      '@typescript-eslint/no-var-requires': 'off',
      'no-console': 'off',
      indent: [
        'error',
        2,
        {
          SwitchCase: 1,
          flatTernaryExpressions: true,
          offsetTernaryExpressions: false,
          ignoredNodes: [
            'PropertyDefinition[decorators]',
            'TSUnionType',
            'TSIntersectionType',
            'TSTypeParameterInstantiation',
            'FunctionExpression[params]:has(Identifier[decorators])',
            'FunctionExpression > .params[decorators.length > 0]',
            'FunctionExpression > .params > :matches(Decorator, :not(:first-child))',
            'ClassBody.body > PropertyDefinition[decorators.length > 0] > .key',
            'VariableDeclarator > ArrowFunctionExpression > BlockStatement',
            'VariableDeclarator > ArrowFunctionExpression > CallExpression',
            "CallExpression > ArrowFunctionExpression[body.type='BlockStatement']",
            "CallExpression > FunctionExpression[body.type='BlockStatement']",
            'JSXElement',
            'JSXFragment',
            'JSXOpeningElement',
            'JSXClosingElement',
            'JSXAttribute',
            'JSXSpreadAttribute',
            'JSXText',
            'JSXExpressionContainer',
            'TemplateLiteral',
          ],
        },
      ],
      // React Compiler is not enabled. Preserve the pre-upgrade Hooks policy
      // instead of turning compiler adoption into an implicit lint migration.
      'react-hooks/config': 'off',
      'react-hooks/error-boundaries': 'off',
      'react-hooks/exhaustive-deps': 'off',
      'react-hooks/gating': 'off',
      'react-hooks/globals': 'off',
      'react-hooks/immutability': 'off',
      'react-hooks/incompatible-library': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/set-state-in-render': 'off',
      'react-hooks/static-components': 'off',
      'react-hooks/unsupported-syntax': 'off',
      'react-hooks/use-memo': 'off',
      'react-hooks/void-use-memo': 'off',
      'react/display-name': 'warn',
      '@next/next/no-img-element': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-expressions': ['error', { allowShortCircuit: true }],
    },
  },
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    'dist/**',
    'storybook-static/**',
    'public/iconfont.js',
    'public/webchat/**',
    '**/*.config.js',
    '**/*.config.mjs',
    'scripts/**',
    'server.cert',
    'server.csr',
    'server.js',
    'server.key',
    'enterprise/**',
    'src/app/**/(enterprise)/**',
    'next-env.d.ts',
  ]),
]);
