packages:
  - 'src/app/*'

verifyDepsBeforeRun: false

overrides:
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4
  'antd>@rc-component/tour': 2.4.0

allowBuilds:
  '@parcel/watcher': true
  core-js: false
  core-js-pure: false
  electron: false
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@next/bundle-analyzer@16.3.0'
  - '@next/env@16.3.0'
  - '@next/eslint-plugin-next@16.3.0'
  - '@next/swc-darwin-arm64@16.3.0'
  - '@next/swc-darwin-x64@16.3.0'
  - '@next/swc-linux-arm64-gnu@16.3.0'
  - '@next/swc-linux-arm64-musl@16.3.0'
  - '@next/swc-linux-x64-gnu@16.3.0'
  - '@next/swc-linux-x64-musl@16.3.0'
  - '@next/swc-win32-arm64-msvc@16.3.0'
  - '@next/swc-win32-x64-msvc@16.3.0'
  - eslint-config-next@16.3.0
  - next@16.3.0
